// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_Batch_1_StreamingMaxPool_Pre (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [63:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state5;
reg    out_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire   [2:0] i_fu_720_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln153_fu_746_p2;
wire    ap_CS_fsm_state3;
wire   [2:0] yp_fu_752_p2;
reg   [2:0] yp_reg_1214;
wire   [4:0] add_ln154_fu_764_p2;
reg   [4:0] add_ln154_reg_1222;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln155_fu_770_p2;
reg   [0:0] icmp_ln155_reg_1227;
wire   [0:0] icmp_ln154_fu_758_p2;
wire   [0:0] and_ln155_fu_796_p2;
reg   [0:0] and_ln155_reg_1233;
wire   [2:0] select_ln165_fu_808_p3;
reg   [2:0] select_ln165_reg_1238;
reg   [2:0] buf_0_V_addr_2_reg_1243;
reg   [2:0] buf_1_V_addr_2_reg_1248;
reg   [2:0] buf_2_V_addr_2_reg_1253;
reg   [2:0] buf_3_V_addr_2_reg_1258;
reg   [2:0] buf_4_V_addr_2_reg_1263;
reg   [2:0] buf_5_V_addr_2_reg_1268;
reg   [2:0] buf_6_V_addr_2_reg_1273;
reg   [2:0] buf_7_V_addr_2_reg_1278;
reg   [2:0] buf_8_V_addr_2_reg_1283;
reg   [2:0] buf_9_V_addr_2_reg_1288;
reg   [2:0] buf_10_V_addr_2_reg_1293;
reg   [2:0] buf_11_V_addr_2_reg_1298;
reg   [2:0] buf_12_V_addr_2_reg_1303;
reg   [2:0] buf_13_V_addr_2_reg_1308;
reg   [2:0] buf_14_V_addr_2_reg_1313;
reg   [2:0] buf_15_V_addr_2_reg_1318;
wire   [1:0] kx_fu_1112_p3;
wire   [4:0] select_ln155_1_fu_1126_p3;
wire   [2:0] outpix_fu_1139_p2;
reg   [2:0] outpix_reg_1384;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln173_fu_1133_p2;
reg   [2:0] buf_0_V_address0;
reg    buf_0_V_ce0;
reg    buf_0_V_we0;
reg   [3:0] buf_0_V_d0;
wire   [3:0] buf_0_V_q0;
reg   [2:0] buf_1_V_address0;
reg    buf_1_V_ce0;
reg    buf_1_V_we0;
reg   [3:0] buf_1_V_d0;
wire   [3:0] buf_1_V_q0;
reg   [2:0] buf_2_V_address0;
reg    buf_2_V_ce0;
reg    buf_2_V_we0;
reg   [3:0] buf_2_V_d0;
wire   [3:0] buf_2_V_q0;
reg   [2:0] buf_3_V_address0;
reg    buf_3_V_ce0;
reg    buf_3_V_we0;
reg   [3:0] buf_3_V_d0;
wire   [3:0] buf_3_V_q0;
reg   [2:0] buf_4_V_address0;
reg    buf_4_V_ce0;
reg    buf_4_V_we0;
reg   [3:0] buf_4_V_d0;
wire   [3:0] buf_4_V_q0;
reg   [2:0] buf_5_V_address0;
reg    buf_5_V_ce0;
reg    buf_5_V_we0;
reg   [3:0] buf_5_V_d0;
wire   [3:0] buf_5_V_q0;
reg   [2:0] buf_6_V_address0;
reg    buf_6_V_ce0;
reg    buf_6_V_we0;
reg   [3:0] buf_6_V_d0;
wire   [3:0] buf_6_V_q0;
reg   [2:0] buf_7_V_address0;
reg    buf_7_V_ce0;
reg    buf_7_V_we0;
reg   [3:0] buf_7_V_d0;
wire   [3:0] buf_7_V_q0;
reg   [2:0] buf_8_V_address0;
reg    buf_8_V_ce0;
reg    buf_8_V_we0;
reg   [3:0] buf_8_V_d0;
wire   [3:0] buf_8_V_q0;
reg   [2:0] buf_9_V_address0;
reg    buf_9_V_ce0;
reg    buf_9_V_we0;
reg   [3:0] buf_9_V_d0;
wire   [3:0] buf_9_V_q0;
reg   [2:0] buf_10_V_address0;
reg    buf_10_V_ce0;
reg    buf_10_V_we0;
reg   [3:0] buf_10_V_d0;
wire   [3:0] buf_10_V_q0;
reg   [2:0] buf_11_V_address0;
reg    buf_11_V_ce0;
reg    buf_11_V_we0;
reg   [3:0] buf_11_V_d0;
wire   [3:0] buf_11_V_q0;
reg   [2:0] buf_12_V_address0;
reg    buf_12_V_ce0;
reg    buf_12_V_we0;
reg   [3:0] buf_12_V_d0;
wire   [3:0] buf_12_V_q0;
reg   [2:0] buf_13_V_address0;
reg    buf_13_V_ce0;
reg    buf_13_V_we0;
reg   [3:0] buf_13_V_d0;
wire   [3:0] buf_13_V_q0;
reg   [2:0] buf_14_V_address0;
reg    buf_14_V_ce0;
reg    buf_14_V_we0;
reg   [3:0] buf_14_V_d0;
wire   [3:0] buf_14_V_q0;
reg   [2:0] buf_15_V_address0;
reg    buf_15_V_ce0;
reg    buf_15_V_we0;
reg   [3:0] buf_15_V_d0;
wire   [3:0] buf_15_V_q0;
reg   [2:0] i_0_reg_635;
wire   [0:0] icmp_ln146_fu_714_p2;
reg   [2:0] yp_0_reg_646;
reg   [4:0] indvar_flatten45_reg_657;
reg   [4:0] indvar_flatten_reg_668;
reg   [2:0] xp_0_reg_680;
reg   [1:0] kx_0_reg_691;
reg   [2:0] outpix_0_reg_703;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln149_fu_726_p1;
wire   [63:0] zext_ln165_fu_816_p1;
wire   [63:0] zext_ln178_fu_1145_p1;
wire   [0:0] icmp_ln895_fu_841_p2;
wire   [3:0] trunc_ln647_fu_836_p1;
wire   [0:0] icmp_ln895_1_fu_858_p2;
wire   [3:0] p_Result_1_fu_847_p4;
wire   [0:0] icmp_ln895_2_fu_875_p2;
wire   [3:0] p_Result_s_fu_864_p4;
wire   [0:0] icmp_ln895_3_fu_892_p2;
wire   [3:0] p_Result_3_fu_881_p4;
wire   [0:0] icmp_ln895_4_fu_909_p2;
wire   [3:0] p_Result_4_fu_898_p4;
wire   [0:0] icmp_ln895_5_fu_926_p2;
wire   [3:0] p_Result_5_fu_915_p4;
wire   [0:0] icmp_ln895_6_fu_943_p2;
wire   [3:0] p_Result_6_fu_932_p4;
wire   [0:0] icmp_ln895_7_fu_960_p2;
wire   [3:0] p_Result_7_fu_949_p4;
wire   [0:0] icmp_ln895_8_fu_977_p2;
wire   [3:0] p_Result_8_fu_966_p4;
wire   [0:0] icmp_ln895_9_fu_994_p2;
wire   [3:0] p_Result_9_fu_983_p4;
wire   [0:0] icmp_ln895_10_fu_1011_p2;
wire   [3:0] p_Result_2_fu_1000_p4;
wire   [0:0] icmp_ln895_11_fu_1028_p2;
wire   [3:0] p_Result_10_fu_1017_p4;
wire   [0:0] icmp_ln895_12_fu_1045_p2;
wire   [3:0] p_Result_11_fu_1034_p4;
wire   [0:0] icmp_ln895_13_fu_1062_p2;
wire   [3:0] p_Result_12_fu_1051_p4;
wire   [0:0] icmp_ln895_14_fu_1079_p2;
wire   [3:0] p_Result_13_fu_1068_p4;
wire   [0:0] icmp_ln895_15_fu_1096_p2;
wire   [3:0] p_Result_14_fu_1085_p4;
wire   [0:0] icmp_ln157_fu_790_p2;
wire   [0:0] xor_ln155_fu_784_p2;
wire   [2:0] select_ln155_fu_776_p3;
wire   [2:0] xp_fu_802_p2;
wire   [0:0] or_ln157_fu_1108_p2;
wire   [1:0] add_ln157_fu_1102_p2;
wire   [4:0] add_ln155_1_fu_1120_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_0_V_address0),
    .ce0(buf_0_V_ce0),
    .we0(buf_0_V_we0),
    .d0(buf_0_V_d0),
    .q0(buf_0_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_1_V_address0),
    .ce0(buf_1_V_ce0),
    .we0(buf_1_V_we0),
    .d0(buf_1_V_d0),
    .q0(buf_1_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2_V_address0),
    .ce0(buf_2_V_ce0),
    .we0(buf_2_V_we0),
    .d0(buf_2_V_d0),
    .q0(buf_2_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_3_V_address0),
    .ce0(buf_3_V_ce0),
    .we0(buf_3_V_we0),
    .d0(buf_3_V_d0),
    .q0(buf_3_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_4_V_address0),
    .ce0(buf_4_V_ce0),
    .we0(buf_4_V_we0),
    .d0(buf_4_V_d0),
    .q0(buf_4_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_5_V_address0),
    .ce0(buf_5_V_ce0),
    .we0(buf_5_V_we0),
    .d0(buf_5_V_d0),
    .q0(buf_5_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_6_V_address0),
    .ce0(buf_6_V_ce0),
    .we0(buf_6_V_we0),
    .d0(buf_6_V_d0),
    .q0(buf_6_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_7_V_address0),
    .ce0(buf_7_V_ce0),
    .we0(buf_7_V_we0),
    .d0(buf_7_V_d0),
    .q0(buf_7_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_8_V_address0),
    .ce0(buf_8_V_ce0),
    .we0(buf_8_V_we0),
    .d0(buf_8_V_d0),
    .q0(buf_8_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_9_V_address0),
    .ce0(buf_9_V_ce0),
    .we0(buf_9_V_we0),
    .d0(buf_9_V_d0),
    .q0(buf_9_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_10_V_address0),
    .ce0(buf_10_V_ce0),
    .we0(buf_10_V_we0),
    .d0(buf_10_V_d0),
    .q0(buf_10_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_11_V_address0),
    .ce0(buf_11_V_ce0),
    .we0(buf_11_V_we0),
    .d0(buf_11_V_d0),
    .q0(buf_11_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_12_V_address0),
    .ce0(buf_12_V_ce0),
    .we0(buf_12_V_we0),
    .d0(buf_12_V_d0),
    .q0(buf_12_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_13_V_address0),
    .ce0(buf_13_V_ce0),
    .we0(buf_13_V_we0),
    .d0(buf_13_V_d0),
    .q0(buf_13_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_14_V_address0),
    .ce0(buf_14_V_ce0),
    .we0(buf_14_V_we0),
    .d0(buf_14_V_d0),
    .q0(buf_14_V_q0)
);

StreamingMaxPool_Batch_1_StreamingMaxPool_bkb #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
buf_15_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_15_V_address0),
    .ce0(buf_15_V_ce0),
    .we0(buf_15_V_we0),
    .d0(buf_15_V_d0),
    .q0(buf_15_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_reg_635 <= i_fu_720_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_635 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_746_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten45_reg_657 <= 5'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten45_reg_657 <= add_ln154_reg_1222;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_746_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten_reg_668 <= 5'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten_reg_668 <= select_ln155_1_fu_1126_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_746_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        kx_0_reg_691 <= 2'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        kx_0_reg_691 <= kx_fu_1112_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        outpix_0_reg_703 <= 3'd0;
    end else if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        outpix_0_reg_703 <= outpix_reg_1384;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_746_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        xp_0_reg_680 <= 3'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        xp_0_reg_680 <= select_ln165_reg_1238;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln146_fu_714_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        yp_0_reg_646 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln173_fu_1133_p2 == 1'd1))) begin
        yp_0_reg_646 <= yp_reg_1214;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln154_reg_1222 <= add_ln154_fu_764_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln154_fu_758_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln155_reg_1233 <= and_ln155_fu_796_p2;
        buf_0_V_addr_2_reg_1243 <= zext_ln165_fu_816_p1;
        buf_10_V_addr_2_reg_1293 <= zext_ln165_fu_816_p1;
        buf_11_V_addr_2_reg_1298 <= zext_ln165_fu_816_p1;
        buf_12_V_addr_2_reg_1303 <= zext_ln165_fu_816_p1;
        buf_13_V_addr_2_reg_1308 <= zext_ln165_fu_816_p1;
        buf_14_V_addr_2_reg_1313 <= zext_ln165_fu_816_p1;
        buf_15_V_addr_2_reg_1318 <= zext_ln165_fu_816_p1;
        buf_1_V_addr_2_reg_1248 <= zext_ln165_fu_816_p1;
        buf_2_V_addr_2_reg_1253 <= zext_ln165_fu_816_p1;
        buf_3_V_addr_2_reg_1258 <= zext_ln165_fu_816_p1;
        buf_4_V_addr_2_reg_1263 <= zext_ln165_fu_816_p1;
        buf_5_V_addr_2_reg_1268 <= zext_ln165_fu_816_p1;
        buf_6_V_addr_2_reg_1273 <= zext_ln165_fu_816_p1;
        buf_7_V_addr_2_reg_1278 <= zext_ln165_fu_816_p1;
        buf_8_V_addr_2_reg_1283 <= zext_ln165_fu_816_p1;
        buf_9_V_addr_2_reg_1288 <= zext_ln165_fu_816_p1;
        icmp_ln155_reg_1227 <= icmp_ln155_fu_770_p2;
        select_ln165_reg_1238 <= select_ln165_fu_808_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        outpix_reg_1384 <= outpix_fu_1139_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        yp_reg_1214 <= yp_fu_752_p2;
    end
end

always @ (*) begin
    if ((((icmp_ln153_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln153_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_0_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_0_V_address0 = buf_0_V_addr_2_reg_1243;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_0_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_0_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_ce0 = 1'b1;
    end else begin
        buf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_0_V_d0 = trunc_ln647_fu_836_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_d0 = 4'd0;
    end else begin
        buf_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_fu_841_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_we0 = 1'b1;
    end else begin
        buf_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_10_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_10_V_address0 = buf_10_V_addr_2_reg_1293;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_10_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_10_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_10_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_ce0 = 1'b1;
    end else begin
        buf_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_10_V_d0 = {{in_V_V_TDATA[43:40]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_d0 = 4'd0;
    end else begin
        buf_10_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_10_fu_1011_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_we0 = 1'b1;
    end else begin
        buf_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_11_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_11_V_address0 = buf_11_V_addr_2_reg_1298;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_11_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_11_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_11_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_ce0 = 1'b1;
    end else begin
        buf_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_11_V_d0 = {{in_V_V_TDATA[47:44]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_d0 = 4'd0;
    end else begin
        buf_11_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_11_fu_1028_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_we0 = 1'b1;
    end else begin
        buf_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_12_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_12_V_address0 = buf_12_V_addr_2_reg_1303;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_12_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_12_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_12_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_ce0 = 1'b1;
    end else begin
        buf_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_12_V_d0 = {{in_V_V_TDATA[51:48]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_d0 = 4'd0;
    end else begin
        buf_12_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_12_fu_1045_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_we0 = 1'b1;
    end else begin
        buf_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_13_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_13_V_address0 = buf_13_V_addr_2_reg_1308;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_13_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_13_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_13_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_ce0 = 1'b1;
    end else begin
        buf_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_13_V_d0 = {{in_V_V_TDATA[55:52]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_d0 = 4'd0;
    end else begin
        buf_13_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_13_fu_1062_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_we0 = 1'b1;
    end else begin
        buf_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_14_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_14_V_address0 = buf_14_V_addr_2_reg_1313;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_14_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_14_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_14_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_ce0 = 1'b1;
    end else begin
        buf_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_14_V_d0 = {{in_V_V_TDATA[59:56]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_d0 = 4'd0;
    end else begin
        buf_14_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_14_fu_1079_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_we0 = 1'b1;
    end else begin
        buf_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_15_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_15_V_address0 = buf_15_V_addr_2_reg_1318;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_15_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_15_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_15_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_ce0 = 1'b1;
    end else begin
        buf_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_15_V_d0 = {{in_V_V_TDATA[63:60]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_d0 = 4'd0;
    end else begin
        buf_15_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_15_fu_1096_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_we0 = 1'b1;
    end else begin
        buf_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_1_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_V_address0 = buf_1_V_addr_2_reg_1248;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_1_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_1_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_ce0 = 1'b1;
    end else begin
        buf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_V_d0 = {{in_V_V_TDATA[7:4]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_d0 = 4'd0;
    end else begin
        buf_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_1_fu_858_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_we0 = 1'b1;
    end else begin
        buf_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_2_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_V_address0 = buf_2_V_addr_2_reg_1253;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_2_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_2_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_ce0 = 1'b1;
    end else begin
        buf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_V_d0 = {{in_V_V_TDATA[11:8]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_d0 = 4'd0;
    end else begin
        buf_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_2_fu_875_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_we0 = 1'b1;
    end else begin
        buf_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_3_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_V_address0 = buf_3_V_addr_2_reg_1258;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_3_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_3_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_ce0 = 1'b1;
    end else begin
        buf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_V_d0 = {{in_V_V_TDATA[15:12]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_d0 = 4'd0;
    end else begin
        buf_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_3_fu_892_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_we0 = 1'b1;
    end else begin
        buf_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_4_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_V_address0 = buf_4_V_addr_2_reg_1263;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_4_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_4_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_ce0 = 1'b1;
    end else begin
        buf_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_V_d0 = {{in_V_V_TDATA[19:16]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_d0 = 4'd0;
    end else begin
        buf_4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_4_fu_909_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_we0 = 1'b1;
    end else begin
        buf_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_5_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_V_address0 = buf_5_V_addr_2_reg_1268;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_5_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_5_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_ce0 = 1'b1;
    end else begin
        buf_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_V_d0 = {{in_V_V_TDATA[23:20]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_d0 = 4'd0;
    end else begin
        buf_5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_5_fu_926_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_we0 = 1'b1;
    end else begin
        buf_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_6_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_V_address0 = buf_6_V_addr_2_reg_1273;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_6_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_6_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_6_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_ce0 = 1'b1;
    end else begin
        buf_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_V_d0 = {{in_V_V_TDATA[27:24]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_d0 = 4'd0;
    end else begin
        buf_6_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_6_fu_943_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_we0 = 1'b1;
    end else begin
        buf_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_7_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_7_V_address0 = buf_7_V_addr_2_reg_1278;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_7_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_7_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_7_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_ce0 = 1'b1;
    end else begin
        buf_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_7_V_d0 = {{in_V_V_TDATA[31:28]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_d0 = 4'd0;
    end else begin
        buf_7_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_7_fu_960_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_we0 = 1'b1;
    end else begin
        buf_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_8_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_8_V_address0 = buf_8_V_addr_2_reg_1283;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_8_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_8_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_8_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_ce0 = 1'b1;
    end else begin
        buf_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_8_V_d0 = {{in_V_V_TDATA[35:32]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_d0 = 4'd0;
    end else begin
        buf_8_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_8_fu_977_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_we0 = 1'b1;
    end else begin
        buf_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_9_V_address0 = zext_ln178_fu_1145_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_9_V_address0 = buf_9_V_addr_2_reg_1288;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_9_V_address0 = zext_ln165_fu_816_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_9_V_address0 = zext_ln149_fu_726_p1;
    end else begin
        buf_9_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_ce0 = 1'b1;
    end else begin
        buf_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_9_V_d0 = {{in_V_V_TDATA[39:36]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_d0 = 4'd0;
    end else begin
        buf_9_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_714_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_9_fu_994_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_we0 = 1'b1;
    end else begin
        buf_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln146_fu_714_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln153_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln154_fu_758_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln173_fu_1133_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln154_fu_764_p2 = (indvar_flatten45_reg_657 + 5'd1);

assign add_ln155_1_fu_1120_p2 = (indvar_flatten_reg_668 + 5'd1);

assign add_ln157_fu_1102_p2 = (kx_0_reg_691 + 2'd1);

assign and_ln155_fu_796_p2 = (xor_ln155_fu_784_p2 & icmp_ln157_fu_790_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign i_fu_720_p2 = (i_0_reg_635 + 3'd1);

assign icmp_ln146_fu_714_p2 = ((i_0_reg_635 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln153_fu_746_p2 = ((yp_0_reg_646 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_758_p2 = ((indvar_flatten45_reg_657 == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_770_p2 = ((indvar_flatten_reg_668 == 5'd10) ? 1'b1 : 1'b0);

assign icmp_ln157_fu_790_p2 = ((kx_0_reg_691 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_1133_p2 = ((outpix_0_reg_703 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln895_10_fu_1011_p2 = ((p_Result_2_fu_1000_p4 > buf_10_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_11_fu_1028_p2 = ((p_Result_10_fu_1017_p4 > buf_11_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_12_fu_1045_p2 = ((p_Result_11_fu_1034_p4 > buf_12_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_13_fu_1062_p2 = ((p_Result_12_fu_1051_p4 > buf_13_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_14_fu_1079_p2 = ((p_Result_13_fu_1068_p4 > buf_14_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_15_fu_1096_p2 = ((p_Result_14_fu_1085_p4 > buf_15_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_858_p2 = ((p_Result_1_fu_847_p4 > buf_1_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_875_p2 = ((p_Result_s_fu_864_p4 > buf_2_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_892_p2 = ((p_Result_3_fu_881_p4 > buf_3_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_909_p2 = ((p_Result_4_fu_898_p4 > buf_4_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_5_fu_926_p2 = ((p_Result_5_fu_915_p4 > buf_5_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_6_fu_943_p2 = ((p_Result_6_fu_932_p4 > buf_6_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_7_fu_960_p2 = ((p_Result_7_fu_949_p4 > buf_7_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_8_fu_977_p2 = ((p_Result_8_fu_966_p4 > buf_8_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_9_fu_994_p2 = ((p_Result_9_fu_983_p4 > buf_9_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_841_p2 = ((trunc_ln647_fu_836_p1 > buf_0_V_q0) ? 1'b1 : 1'b0);

assign kx_fu_1112_p3 = ((or_ln157_fu_1108_p2[0:0] === 1'b1) ? 2'd1 : add_ln157_fu_1102_p2);

assign or_ln157_fu_1108_p2 = (icmp_ln155_reg_1227 | and_ln155_reg_1233);

assign out_V_V_TDATA = {{{{{{{{{{{{{{{{buf_15_V_q0}, {buf_14_V_q0}}, {buf_13_V_q0}}, {buf_12_V_q0}}, {buf_11_V_q0}}, {buf_10_V_q0}}, {buf_9_V_q0}}, {buf_8_V_q0}}, {buf_7_V_q0}}, {buf_6_V_q0}}, {buf_5_V_q0}}, {buf_4_V_q0}}, {buf_3_V_q0}}, {buf_2_V_q0}}, {buf_1_V_q0}}, {buf_0_V_q0}};

assign outpix_fu_1139_p2 = (outpix_0_reg_703 + 3'd1);

assign p_Result_10_fu_1017_p4 = {{in_V_V_TDATA[47:44]}};

assign p_Result_11_fu_1034_p4 = {{in_V_V_TDATA[51:48]}};

assign p_Result_12_fu_1051_p4 = {{in_V_V_TDATA[55:52]}};

assign p_Result_13_fu_1068_p4 = {{in_V_V_TDATA[59:56]}};

assign p_Result_14_fu_1085_p4 = {{in_V_V_TDATA[63:60]}};

assign p_Result_1_fu_847_p4 = {{in_V_V_TDATA[7:4]}};

assign p_Result_2_fu_1000_p4 = {{in_V_V_TDATA[43:40]}};

assign p_Result_3_fu_881_p4 = {{in_V_V_TDATA[15:12]}};

assign p_Result_4_fu_898_p4 = {{in_V_V_TDATA[19:16]}};

assign p_Result_5_fu_915_p4 = {{in_V_V_TDATA[23:20]}};

assign p_Result_6_fu_932_p4 = {{in_V_V_TDATA[27:24]}};

assign p_Result_7_fu_949_p4 = {{in_V_V_TDATA[31:28]}};

assign p_Result_8_fu_966_p4 = {{in_V_V_TDATA[35:32]}};

assign p_Result_9_fu_983_p4 = {{in_V_V_TDATA[39:36]}};

assign p_Result_s_fu_864_p4 = {{in_V_V_TDATA[11:8]}};

assign select_ln155_1_fu_1126_p3 = ((icmp_ln155_reg_1227[0:0] === 1'b1) ? 5'd1 : add_ln155_1_fu_1120_p2);

assign select_ln155_fu_776_p3 = ((icmp_ln155_fu_770_p2[0:0] === 1'b1) ? 3'd0 : xp_0_reg_680);

assign select_ln165_fu_808_p3 = ((and_ln155_fu_796_p2[0:0] === 1'b1) ? xp_fu_802_p2 : select_ln155_fu_776_p3);

assign trunc_ln647_fu_836_p1 = in_V_V_TDATA[3:0];

assign xor_ln155_fu_784_p2 = (icmp_ln155_fu_770_p2 ^ 1'd1);

assign xp_fu_802_p2 = (3'd1 + select_ln155_fu_776_p3);

assign yp_fu_752_p2 = (yp_0_reg_646 + 3'd1);

assign zext_ln149_fu_726_p1 = i_0_reg_635;

assign zext_ln165_fu_816_p1 = select_ln165_fu_808_p3;

assign zext_ln178_fu_1145_p1 = outpix_0_reg_703;

endmodule //StreamingMaxPool_Batch_1_StreamingMaxPool_Pre
