// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_0_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weight_V_V_TDATA,
        weight_V_V_TVALID,
        weight_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [103:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
input  [79:0] weight_V_V_TDATA;
input   weight_V_V_TVALID;
output   weight_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weight_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] threshs_m_thresholds_14_address0;
reg    threshs_m_thresholds_14_ce0;
wire   [5:0] threshs_m_thresholds_14_q0;
wire   [2:0] threshs_m_thresholds_13_address0;
reg    threshs_m_thresholds_13_ce0;
wire   [5:0] threshs_m_thresholds_13_q0;
wire   [2:0] threshs_m_thresholds_7_address0;
reg    threshs_m_thresholds_7_ce0;
wire   [5:0] threshs_m_thresholds_7_q0;
wire   [2:0] threshs_m_thresholds_6_address0;
reg    threshs_m_thresholds_6_ce0;
wire   [5:0] threshs_m_thresholds_6_q0;
wire   [2:0] threshs_m_thresholds_5_address0;
reg    threshs_m_thresholds_5_ce0;
wire   [5:0] threshs_m_thresholds_5_q0;
wire   [2:0] threshs_m_thresholds_4_address0;
reg    threshs_m_thresholds_4_ce0;
wire   [6:0] threshs_m_thresholds_4_q0;
wire   [2:0] threshs_m_thresholds_3_address0;
reg    threshs_m_thresholds_3_ce0;
wire   [6:0] threshs_m_thresholds_3_q0;
wire   [2:0] threshs_m_thresholds_2_address0;
reg    threshs_m_thresholds_2_ce0;
wire   [6:0] threshs_m_thresholds_2_q0;
wire   [2:0] threshs_m_thresholds_1_address0;
reg    threshs_m_thresholds_1_ce0;
wire   [6:0] threshs_m_thresholds_1_q0;
wire   [2:0] threshs_m_thresholds_address0;
reg    threshs_m_thresholds_ce0;
wire   [6:0] threshs_m_thresholds_q0;
wire   [2:0] threshs_m_thresholds_12_address0;
reg    threshs_m_thresholds_12_ce0;
wire   [6:0] threshs_m_thresholds_12_q0;
wire   [2:0] threshs_m_thresholds_11_address0;
reg    threshs_m_thresholds_11_ce0;
wire   [6:0] threshs_m_thresholds_11_q0;
wire   [2:0] threshs_m_thresholds_10_address0;
reg    threshs_m_thresholds_10_ce0;
wire   [6:0] threshs_m_thresholds_10_q0;
wire   [2:0] threshs_m_thresholds_9_address0;
reg    threshs_m_thresholds_9_ce0;
wire   [7:0] threshs_m_thresholds_9_q0;
wire   [2:0] threshs_m_thresholds_8_address0;
reg    threshs_m_thresholds_8_ce0;
wire   [7:0] threshs_m_thresholds_8_q0;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln248_fu_487_p2;
wire   [0:0] icmp_ln252_fu_502_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln271_reg_2300;
reg    weight_V_V_TDATA_blk_n;
reg   [12:0] i_0_reg_466;
reg    ap_predicate_op26_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] i_fu_493_p2;
wire   [2:0] wgt_M_instance_0_V_fu_517_p1;
reg  signed [2:0] wgt_M_instance_0_V_reg_2175;
reg  signed [2:0] wgt_M_instance_1_V_reg_2180;
reg  signed [2:0] wgt_M_instance_2_V_reg_2185;
reg  signed [2:0] wgt_M_instance_3_V_reg_2190;
reg  signed [2:0] wgt_M_instance_4_V_reg_2195;
reg  signed [2:0] wgt_M_instance_5_V_reg_2200;
reg  signed [2:0] wgt_M_instance_6_V_reg_2205;
reg  signed [2:0] wgt_M_instance_7_V_reg_2210;
reg  signed [2:0] wgt_M_instance_8_V_reg_2215;
reg  signed [2:0] wgt_M_instance_9_V_reg_2220;
reg  signed [2:0] wgt_M_instance_10_s_reg_2225;
reg  signed [2:0] wgt_M_instance_11_s_reg_2230;
reg  signed [2:0] wgt_M_instance_12_s_reg_2235;
reg  signed [2:0] wgt_M_instance_13_s_reg_2240;
reg  signed [2:0] wgt_M_instance_14_s_reg_2245;
reg  signed [2:0] wgt_M_instance_15_s_reg_2250;
reg  signed [2:0] wgt_M_instance_16_s_reg_2255;
reg  signed [2:0] wgt_M_instance_17_s_reg_2260;
reg  signed [2:0] wgt_M_instance_18_s_reg_2265;
reg  signed [2:0] wgt_M_instance_19_s_reg_2270;
reg  signed [2:0] wgt_M_instance_20_s_reg_2275;
reg  signed [2:0] wgt_M_instance_21_s_reg_2280;
reg  signed [2:0] wgt_M_instance_22_s_reg_2285;
reg  signed [2:0] wgt_M_instance_23_s_reg_2290;
reg  signed [2:0] wgt_M_instance_24_s_reg_2295;
wire   [0:0] icmp_ln271_fu_770_p2;
wire   [10:0] add_ln700_24_fu_1653_p2;
reg   [10:0] add_ln700_24_reg_2304;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire   [63:0] zext_ln186_fu_1678_p1;
reg   [10:0] accu_V_0_0_0_fu_236;
reg   [31:0] sf_1_fu_240;
wire   [31:0] sf_fu_1659_p2;
reg   [31:0] nf_assign_fu_244;
wire   [31:0] nf_1_fu_1709_p3;
reg   [31:0] ap_sig_allocacmp_nf_assign_load_1;
reg   [99:0] inElem_V_fu_248;
wire   [99:0] tmp_V_2_fu_508_p1;
reg    ap_block_pp0_stage0_01001;
wire  signed [3:0] trunc_ln647_fu_784_p1;
wire  signed [6:0] mul_ln1352_fu_795_p2;
wire  signed [3:0] arg_V_read_assign_1_fu_805_p4;
wire  signed [6:0] mul_ln1352_1_fu_822_p2;
wire  signed [3:0] arg_V_read_assign_2_fu_832_p4;
wire  signed [6:0] mul_ln1352_2_fu_849_p2;
wire  signed [3:0] arg_V_read_assign_3_fu_859_p4;
wire  signed [6:0] mul_ln1352_3_fu_876_p2;
wire  signed [3:0] arg_V_read_assign_4_fu_886_p4;
wire  signed [6:0] mul_ln1352_4_fu_903_p2;
wire  signed [3:0] arg_V_read_assign_5_fu_913_p4;
wire  signed [6:0] mul_ln1352_5_fu_930_p2;
wire  signed [3:0] arg_V_read_assign_6_fu_940_p4;
wire  signed [6:0] mul_ln1352_6_fu_957_p2;
wire  signed [3:0] arg_V_read_assign_7_fu_967_p4;
wire  signed [6:0] mul_ln1352_7_fu_984_p2;
wire  signed [3:0] arg_V_read_assign_8_fu_994_p4;
wire  signed [6:0] mul_ln1352_8_fu_1011_p2;
wire  signed [3:0] arg_V_read_assign_9_fu_1021_p4;
wire  signed [6:0] mul_ln1352_9_fu_1038_p2;
wire  signed [3:0] arg_V_read_assign_s_fu_1048_p4;
wire  signed [6:0] mul_ln1352_10_fu_1065_p2;
wire  signed [3:0] arg_V_read_assign_10_fu_1075_p4;
wire  signed [6:0] mul_ln1352_11_fu_1092_p2;
wire  signed [3:0] arg_V_read_assign_11_fu_1102_p4;
wire  signed [6:0] mul_ln1352_12_fu_1119_p2;
wire  signed [3:0] arg_V_read_assign_12_fu_1129_p4;
wire  signed [6:0] mul_ln1352_13_fu_1146_p2;
wire  signed [3:0] arg_V_read_assign_13_fu_1156_p4;
wire  signed [6:0] mul_ln1352_14_fu_1173_p2;
wire  signed [3:0] arg_V_read_assign_14_fu_1183_p4;
wire  signed [6:0] mul_ln1352_15_fu_1200_p2;
wire  signed [3:0] arg_V_read_assign_15_fu_1210_p4;
wire  signed [6:0] mul_ln1352_16_fu_1227_p2;
wire  signed [3:0] arg_V_read_assign_16_fu_1237_p4;
wire  signed [6:0] mul_ln1352_17_fu_1254_p2;
wire  signed [3:0] arg_V_read_assign_17_fu_1264_p4;
wire  signed [6:0] mul_ln1352_18_fu_1281_p2;
wire  signed [3:0] arg_V_read_assign_18_fu_1291_p4;
wire  signed [6:0] mul_ln1352_19_fu_1308_p2;
wire  signed [3:0] arg_V_read_assign_19_fu_1318_p4;
wire  signed [6:0] mul_ln1352_20_fu_1335_p2;
wire  signed [3:0] arg_V_read_assign_20_fu_1345_p4;
wire  signed [6:0] mul_ln1352_21_fu_1362_p2;
wire  signed [3:0] arg_V_read_assign_21_fu_1372_p4;
wire  signed [6:0] mul_ln1352_22_fu_1389_p2;
wire  signed [3:0] arg_V_read_assign_22_fu_1399_p4;
wire  signed [6:0] mul_ln1352_23_fu_1416_p2;
wire  signed [3:0] arg_V_read_assign_23_fu_1426_p4;
wire  signed [6:0] mul_ln1352_24_fu_1443_p2;
wire  signed [7:0] sext_ln170_22_fu_1395_p1;
wire  signed [7:0] sext_ln170_23_fu_1422_p1;
wire   [7:0] add_ln700_fu_1453_p2;
wire  signed [10:0] sext_ln700_1_fu_1459_p1;
wire   [10:0] res_V_fu_776_p3;
wire  signed [7:0] sext_ln170_20_fu_1341_p1;
wire  signed [7:0] sext_ln170_17_fu_1260_p1;
wire   [7:0] add_ln700_2_fu_1469_p2;
wire  signed [7:0] sext_ln170_21_fu_1368_p1;
wire   [7:0] add_ln700_3_fu_1475_p2;
wire  signed [10:0] sext_ln700_2_fu_1481_p1;
wire   [10:0] add_ln700_1_fu_1463_p2;
wire  signed [7:0] sext_ln170_18_fu_1287_p1;
wire  signed [7:0] sext_ln170_11_fu_1098_p1;
wire   [7:0] add_ln700_5_fu_1491_p2;
wire  signed [7:0] sext_ln170_19_fu_1314_p1;
wire   [7:0] add_ln700_6_fu_1497_p2;
wire  signed [7:0] sext_ln170_13_fu_1152_p1;
wire  signed [7:0] sext_ln170_12_fu_1125_p1;
wire   [7:0] add_ln700_7_fu_1507_p2;
wire  signed [7:0] sext_ln170_14_fu_1179_p1;
wire  signed [7:0] sext_ln170_16_fu_1233_p1;
wire   [7:0] add_ln700_8_fu_1517_p2;
wire  signed [8:0] sext_ln700_5_fu_1523_p1;
wire  signed [8:0] sext_ln700_4_fu_1513_p1;
wire   [8:0] add_ln700_9_fu_1527_p2;
wire  signed [8:0] sext_ln700_3_fu_1503_p1;
wire   [8:0] add_ln700_10_fu_1533_p2;
wire  signed [10:0] sext_ln700_6_fu_1539_p1;
wire   [10:0] add_ln700_4_fu_1485_p2;
wire  signed [7:0] sext_ln170_1_fu_828_p1;
wire  signed [7:0] sext_ln170_fu_801_p1;
wire   [7:0] add_ln700_12_fu_1549_p2;
wire  signed [7:0] sext_ln170_15_fu_1206_p1;
wire   [7:0] add_ln700_13_fu_1555_p2;
wire  signed [7:0] sext_ln170_4_fu_909_p1;
wire  signed [7:0] sext_ln170_3_fu_882_p1;
wire   [7:0] add_ln700_14_fu_1565_p2;
wire  signed [7:0] sext_ln170_2_fu_855_p1;
wire   [7:0] add_ln700_15_fu_1571_p2;
wire  signed [8:0] sext_ln700_8_fu_1577_p1;
wire  signed [8:0] sext_ln700_7_fu_1561_p1;
wire   [8:0] add_ln700_16_fu_1581_p2;
wire  signed [7:0] sext_ln170_7_fu_990_p1;
wire  signed [7:0] sext_ln170_6_fu_963_p1;
wire   [7:0] add_ln700_17_fu_1591_p2;
wire  signed [7:0] sext_ln170_5_fu_936_p1;
wire   [7:0] add_ln700_18_fu_1597_p2;
wire  signed [7:0] sext_ln170_8_fu_1017_p1;
wire  signed [7:0] sext_ln170_10_fu_1071_p1;
wire   [7:0] add_ln700_19_fu_1607_p2;
wire  signed [7:0] sext_ln170_9_fu_1044_p1;
wire  signed [7:0] sext_ln700_fu_1449_p1;
wire   [7:0] add_ln700_20_fu_1617_p2;
wire  signed [8:0] sext_ln700_12_fu_1623_p1;
wire  signed [8:0] sext_ln700_11_fu_1613_p1;
wire   [8:0] add_ln700_21_fu_1627_p2;
wire  signed [8:0] sext_ln700_10_fu_1603_p1;
wire   [8:0] add_ln700_22_fu_1633_p2;
wire  signed [9:0] sext_ln700_13_fu_1639_p1;
wire  signed [9:0] sext_ln700_9_fu_1587_p1;
wire   [9:0] add_ln700_23_fu_1643_p2;
wire  signed [10:0] sext_ln700_14_fu_1649_p1;
wire   [10:0] add_ln700_11_fu_1543_p2;
wire   [31:0] nf_fu_1697_p2;
wire   [0:0] icmp_ln301_fu_1703_p2;
wire  signed [10:0] sext_ln186_fu_1722_p1;
wire   [0:0] icmp_ln899_fu_1726_p2;
wire   [0:0] xor_ln899_fu_1731_p2;
wire   [10:0] zext_ln186_2_fu_1741_p1;
wire   [0:0] icmp_ln899_1_fu_1745_p2;
wire   [0:0] xor_ln899_1_fu_1750_p2;
wire   [10:0] zext_ln186_4_fu_1760_p1;
wire   [0:0] icmp_ln899_2_fu_1764_p2;
wire   [0:0] xor_ln899_2_fu_1769_p2;
wire   [10:0] zext_ln186_6_fu_1779_p1;
wire   [0:0] icmp_ln899_3_fu_1783_p2;
wire   [0:0] xor_ln899_3_fu_1788_p2;
wire   [10:0] zext_ln186_8_fu_1798_p1;
wire   [0:0] icmp_ln899_4_fu_1802_p2;
wire   [0:0] xor_ln899_4_fu_1807_p2;
wire   [10:0] zext_ln186_10_fu_1817_p1;
wire   [0:0] icmp_ln899_5_fu_1821_p2;
wire   [0:0] xor_ln899_5_fu_1826_p2;
wire   [10:0] zext_ln186_12_fu_1836_p1;
wire   [0:0] icmp_ln899_6_fu_1840_p2;
wire   [0:0] xor_ln899_6_fu_1845_p2;
wire   [10:0] zext_ln186_14_fu_1855_p1;
wire   [0:0] icmp_ln899_7_fu_1859_p2;
wire   [0:0] xor_ln899_7_fu_1864_p2;
wire   [10:0] zext_ln186_16_fu_1874_p1;
wire   [0:0] icmp_ln899_8_fu_1878_p2;
wire   [0:0] xor_ln899_8_fu_1883_p2;
wire   [10:0] zext_ln186_18_fu_1893_p1;
wire   [0:0] icmp_ln899_9_fu_1897_p2;
wire   [0:0] xor_ln899_9_fu_1902_p2;
wire   [10:0] zext_ln186_20_fu_1912_p1;
wire   [0:0] icmp_ln899_10_fu_1916_p2;
wire   [0:0] xor_ln899_10_fu_1921_p2;
wire   [10:0] zext_ln186_22_fu_1931_p1;
wire   [0:0] icmp_ln899_11_fu_1935_p2;
wire   [0:0] xor_ln899_11_fu_1940_p2;
wire   [10:0] zext_ln186_24_fu_1950_p1;
wire   [0:0] icmp_ln899_12_fu_1954_p2;
wire   [0:0] xor_ln899_12_fu_1959_p2;
wire   [10:0] zext_ln186_26_fu_1969_p1;
wire   [0:0] icmp_ln899_13_fu_1973_p2;
wire   [0:0] xor_ln899_13_fu_1978_p2;
wire   [10:0] zext_ln186_28_fu_1988_p1;
wire   [0:0] icmp_ln899_14_fu_1992_p2;
wire   [0:0] xor_ln899_14_fu_1997_p2;
wire   [1:0] zext_ln186_3_fu_1756_p1;
wire   [1:0] zext_ln186_5_fu_1775_p1;
wire   [1:0] add_ln700_25_fu_2007_p2;
wire   [1:0] zext_ln186_1_fu_1737_p1;
wire   [1:0] add_ln700_26_fu_2013_p2;
wire   [1:0] zext_ln186_7_fu_1794_p1;
wire   [1:0] zext_ln186_9_fu_1813_p1;
wire   [1:0] add_ln700_27_fu_2023_p2;
wire   [1:0] zext_ln186_11_fu_1832_p1;
wire   [1:0] zext_ln186_13_fu_1851_p1;
wire   [1:0] add_ln700_28_fu_2033_p2;
wire   [2:0] zext_ln700_3_fu_2039_p1;
wire   [2:0] zext_ln700_2_fu_2029_p1;
wire   [2:0] add_ln700_29_fu_2043_p2;
wire   [2:0] zext_ln700_1_fu_2019_p1;
wire   [2:0] add_ln700_30_fu_2049_p2;
wire   [1:0] zext_ln186_15_fu_1870_p1;
wire   [1:0] zext_ln186_17_fu_1889_p1;
wire   [1:0] add_ln700_31_fu_2059_p2;
wire   [1:0] zext_ln186_19_fu_1908_p1;
wire   [1:0] zext_ln186_21_fu_1927_p1;
wire   [1:0] add_ln700_32_fu_2069_p2;
wire   [2:0] zext_ln700_6_fu_2075_p1;
wire   [2:0] zext_ln700_5_fu_2065_p1;
wire   [2:0] add_ln700_33_fu_2079_p2;
wire   [1:0] zext_ln186_23_fu_1946_p1;
wire   [1:0] zext_ln186_25_fu_1965_p1;
wire   [1:0] add_ln700_34_fu_2089_p2;
wire   [1:0] zext_ln186_27_fu_1984_p1;
wire   [1:0] zext_ln700_fu_2003_p1;
wire   [1:0] add_ln700_35_fu_2099_p2;
wire   [2:0] zext_ln700_9_fu_2105_p1;
wire   [2:0] zext_ln700_8_fu_2095_p1;
wire   [2:0] add_ln700_36_fu_2109_p2;
wire   [3:0] zext_ln700_10_fu_2115_p1;
wire   [3:0] zext_ln700_7_fu_2085_p1;
wire   [3:0] add_ln700_37_fu_2119_p2;
wire   [3:0] zext_ln700_4_fu_2055_p1;
wire   [3:0] tmp_V_fu_2125_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_0_Matrix_Vector_Actbkb #(
    .DataWidth( 6 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_14_address0),
    .ce0(threshs_m_thresholds_14_ce0),
    .q0(threshs_m_thresholds_14_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actcud #(
    .DataWidth( 6 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_13_address0),
    .ce0(threshs_m_thresholds_13_ce0),
    .q0(threshs_m_thresholds_13_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActdEe #(
    .DataWidth( 6 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_7_address0),
    .ce0(threshs_m_thresholds_7_ce0),
    .q0(threshs_m_thresholds_7_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActeOg #(
    .DataWidth( 6 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_6_address0),
    .ce0(threshs_m_thresholds_6_ce0),
    .q0(threshs_m_thresholds_6_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActfYi #(
    .DataWidth( 6 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_5_address0),
    .ce0(threshs_m_thresholds_5_ce0),
    .q0(threshs_m_thresholds_5_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actg8j #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_4_address0),
    .ce0(threshs_m_thresholds_4_ce0),
    .q0(threshs_m_thresholds_4_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Acthbi #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_3_address0),
    .ce0(threshs_m_thresholds_3_ce0),
    .q0(threshs_m_thresholds_3_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actibs #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_2_address0),
    .ce0(threshs_m_thresholds_2_ce0),
    .q0(threshs_m_thresholds_2_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActjbC #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_1_address0),
    .ce0(threshs_m_thresholds_1_ce0),
    .q0(threshs_m_thresholds_1_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActkbM #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_address0),
    .ce0(threshs_m_thresholds_ce0),
    .q0(threshs_m_thresholds_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActlbW #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_12_address0),
    .ce0(threshs_m_thresholds_12_ce0),
    .q0(threshs_m_thresholds_12_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actmb6 #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_11_address0),
    .ce0(threshs_m_thresholds_11_ce0),
    .q0(threshs_m_thresholds_11_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actncg #(
    .DataWidth( 7 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_10_address0),
    .ce0(threshs_m_thresholds_10_ce0),
    .q0(threshs_m_thresholds_10_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Actocq #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_9_address0),
    .ce0(threshs_m_thresholds_9_ce0),
    .q0(threshs_m_thresholds_9_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_ActpcA #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
threshs_m_thresholds_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_8_address0),
    .ce0(threshs_m_thresholds_8_ce0),
    .q0(threshs_m_thresholds_8_q0)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U1(
    .din0(trunc_ln647_fu_784_p1),
    .din1(wgt_M_instance_0_V_reg_2175),
    .dout(mul_ln1352_fu_795_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U2(
    .din0(arg_V_read_assign_1_fu_805_p4),
    .din1(wgt_M_instance_1_V_reg_2180),
    .dout(mul_ln1352_1_fu_822_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U3(
    .din0(arg_V_read_assign_2_fu_832_p4),
    .din1(wgt_M_instance_2_V_reg_2185),
    .dout(mul_ln1352_2_fu_849_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U4(
    .din0(arg_V_read_assign_3_fu_859_p4),
    .din1(wgt_M_instance_3_V_reg_2190),
    .dout(mul_ln1352_3_fu_876_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U5(
    .din0(arg_V_read_assign_4_fu_886_p4),
    .din1(wgt_M_instance_4_V_reg_2195),
    .dout(mul_ln1352_4_fu_903_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U6(
    .din0(arg_V_read_assign_5_fu_913_p4),
    .din1(wgt_M_instance_5_V_reg_2200),
    .dout(mul_ln1352_5_fu_930_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U7(
    .din0(arg_V_read_assign_6_fu_940_p4),
    .din1(wgt_M_instance_6_V_reg_2205),
    .dout(mul_ln1352_6_fu_957_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U8(
    .din0(arg_V_read_assign_7_fu_967_p4),
    .din1(wgt_M_instance_7_V_reg_2210),
    .dout(mul_ln1352_7_fu_984_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U9(
    .din0(arg_V_read_assign_8_fu_994_p4),
    .din1(wgt_M_instance_8_V_reg_2215),
    .dout(mul_ln1352_8_fu_1011_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U10(
    .din0(arg_V_read_assign_9_fu_1021_p4),
    .din1(wgt_M_instance_9_V_reg_2220),
    .dout(mul_ln1352_9_fu_1038_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U11(
    .din0(arg_V_read_assign_s_fu_1048_p4),
    .din1(wgt_M_instance_10_s_reg_2225),
    .dout(mul_ln1352_10_fu_1065_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U12(
    .din0(arg_V_read_assign_10_fu_1075_p4),
    .din1(wgt_M_instance_11_s_reg_2230),
    .dout(mul_ln1352_11_fu_1092_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U13(
    .din0(arg_V_read_assign_11_fu_1102_p4),
    .din1(wgt_M_instance_12_s_reg_2235),
    .dout(mul_ln1352_12_fu_1119_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U14(
    .din0(arg_V_read_assign_12_fu_1129_p4),
    .din1(wgt_M_instance_13_s_reg_2240),
    .dout(mul_ln1352_13_fu_1146_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U15(
    .din0(arg_V_read_assign_13_fu_1156_p4),
    .din1(wgt_M_instance_14_s_reg_2245),
    .dout(mul_ln1352_14_fu_1173_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U16(
    .din0(arg_V_read_assign_14_fu_1183_p4),
    .din1(wgt_M_instance_15_s_reg_2250),
    .dout(mul_ln1352_15_fu_1200_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U17(
    .din0(arg_V_read_assign_15_fu_1210_p4),
    .din1(wgt_M_instance_16_s_reg_2255),
    .dout(mul_ln1352_16_fu_1227_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U18(
    .din0(arg_V_read_assign_16_fu_1237_p4),
    .din1(wgt_M_instance_17_s_reg_2260),
    .dout(mul_ln1352_17_fu_1254_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U19(
    .din0(arg_V_read_assign_17_fu_1264_p4),
    .din1(wgt_M_instance_18_s_reg_2265),
    .dout(mul_ln1352_18_fu_1281_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U20(
    .din0(arg_V_read_assign_18_fu_1291_p4),
    .din1(wgt_M_instance_19_s_reg_2270),
    .dout(mul_ln1352_19_fu_1308_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U21(
    .din0(arg_V_read_assign_19_fu_1318_p4),
    .din1(wgt_M_instance_20_s_reg_2275),
    .dout(mul_ln1352_20_fu_1335_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U22(
    .din0(arg_V_read_assign_20_fu_1345_p4),
    .din1(wgt_M_instance_21_s_reg_2280),
    .dout(mul_ln1352_21_fu_1362_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U23(
    .din0(arg_V_read_assign_21_fu_1372_p4),
    .din1(wgt_M_instance_22_s_reg_2285),
    .dout(mul_ln1352_22_fu_1389_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U24(
    .din0(arg_V_read_assign_22_fu_1399_p4),
    .din1(wgt_M_instance_23_s_reg_2290),
    .dout(mul_ln1352_23_fu_1416_p2)
);

StreamingFCLayer_Batch_0_StreamingFCLayer_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
StreamingFCLayer_qcK_U25(
    .din0(arg_V_read_assign_23_fu_1426_p4),
    .din1(wgt_M_instance_24_s_reg_2295),
    .dout(mul_ln1352_24_fu_1443_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_487_p2 == 1'd0))) begin
        i_0_reg_466 <= i_fu_493_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_466 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_770_p2 == 1'd1))) begin
        nf_assign_fu_244 <= nf_1_fu_1709_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_assign_fu_244 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_770_p2 == 1'd0))) begin
        sf_1_fu_240 <= sf_fu_1659_p2;
    end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_770_p2 == 1'd1)))) begin
        sf_1_fu_240 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accu_V_0_0_0_fu_236 <= add_ln700_24_fu_1653_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln700_24_reg_2304 <= add_ln700_24_fu_1653_p2;
        icmp_ln271_reg_2300 <= icmp_ln271_fu_770_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln252_fu_502_p2 == 1'd1) & (icmp_ln248_fu_487_p2 == 1'd0))) begin
        inElem_V_fu_248 <= tmp_V_2_fu_508_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_487_p2 == 1'd0))) begin
        wgt_M_instance_0_V_reg_2175 <= wgt_M_instance_0_V_fu_517_p1;
        wgt_M_instance_10_s_reg_2225 <= {{weight_V_V_TDATA[32:30]}};
        wgt_M_instance_11_s_reg_2230 <= {{weight_V_V_TDATA[35:33]}};
        wgt_M_instance_12_s_reg_2235 <= {{weight_V_V_TDATA[38:36]}};
        wgt_M_instance_13_s_reg_2240 <= {{weight_V_V_TDATA[41:39]}};
        wgt_M_instance_14_s_reg_2245 <= {{weight_V_V_TDATA[44:42]}};
        wgt_M_instance_15_s_reg_2250 <= {{weight_V_V_TDATA[47:45]}};
        wgt_M_instance_16_s_reg_2255 <= {{weight_V_V_TDATA[50:48]}};
        wgt_M_instance_17_s_reg_2260 <= {{weight_V_V_TDATA[53:51]}};
        wgt_M_instance_18_s_reg_2265 <= {{weight_V_V_TDATA[56:54]}};
        wgt_M_instance_19_s_reg_2270 <= {{weight_V_V_TDATA[59:57]}};
        wgt_M_instance_1_V_reg_2180 <= {{weight_V_V_TDATA[5:3]}};
        wgt_M_instance_20_s_reg_2275 <= {{weight_V_V_TDATA[62:60]}};
        wgt_M_instance_21_s_reg_2280 <= {{weight_V_V_TDATA[65:63]}};
        wgt_M_instance_22_s_reg_2285 <= {{weight_V_V_TDATA[68:66]}};
        wgt_M_instance_23_s_reg_2290 <= {{weight_V_V_TDATA[71:69]}};
        wgt_M_instance_24_s_reg_2295 <= {{weight_V_V_TDATA[74:72]}};
        wgt_M_instance_2_V_reg_2185 <= {{weight_V_V_TDATA[8:6]}};
        wgt_M_instance_3_V_reg_2190 <= {{weight_V_V_TDATA[11:9]}};
        wgt_M_instance_4_V_reg_2195 <= {{weight_V_V_TDATA[14:12]}};
        wgt_M_instance_5_V_reg_2200 <= {{weight_V_V_TDATA[17:15]}};
        wgt_M_instance_6_V_reg_2205 <= {{weight_V_V_TDATA[20:18]}};
        wgt_M_instance_7_V_reg_2210 <= {{weight_V_V_TDATA[23:21]}};
        wgt_M_instance_8_V_reg_2215 <= {{weight_V_V_TDATA[26:24]}};
        wgt_M_instance_9_V_reg_2220 <= {{weight_V_V_TDATA[29:27]}};
    end
end

always @ (*) begin
    if ((icmp_ln248_fu_487_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln271_fu_770_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_nf_assign_load_1 = nf_1_fu_1709_p3;
    end else begin
        ap_sig_allocacmp_nf_assign_load_1 = nf_assign_fu_244;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_502_p2 == 1'd1) & (icmp_ln248_fu_487_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op26_read_state2 == 1'b1))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln271_reg_2300 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_2300 == 1'd1))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_10_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_11_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_12_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_13_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_14_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_2_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_3_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_4_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_5_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_6_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_7_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_8_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_9_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln248_fu_487_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        weight_V_V_TDATA_blk_n = weight_V_V_TVALID;
    end else begin
        weight_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_487_p2 == 1'd0))) begin
        weight_V_V_TREADY = 1'b1;
    end else begin
        weight_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln248_fu_487_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln248_fu_487_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_10_fu_1533_p2 = ($signed(add_ln700_9_fu_1527_p2) + $signed(sext_ln700_3_fu_1503_p1));

assign add_ln700_11_fu_1543_p2 = ($signed(sext_ln700_6_fu_1539_p1) + $signed(add_ln700_4_fu_1485_p2));

assign add_ln700_12_fu_1549_p2 = ($signed(sext_ln170_1_fu_828_p1) + $signed(sext_ln170_fu_801_p1));

assign add_ln700_13_fu_1555_p2 = ($signed(add_ln700_12_fu_1549_p2) + $signed(sext_ln170_15_fu_1206_p1));

assign add_ln700_14_fu_1565_p2 = ($signed(sext_ln170_4_fu_909_p1) + $signed(sext_ln170_3_fu_882_p1));

assign add_ln700_15_fu_1571_p2 = ($signed(add_ln700_14_fu_1565_p2) + $signed(sext_ln170_2_fu_855_p1));

assign add_ln700_16_fu_1581_p2 = ($signed(sext_ln700_8_fu_1577_p1) + $signed(sext_ln700_7_fu_1561_p1));

assign add_ln700_17_fu_1591_p2 = ($signed(sext_ln170_7_fu_990_p1) + $signed(sext_ln170_6_fu_963_p1));

assign add_ln700_18_fu_1597_p2 = ($signed(add_ln700_17_fu_1591_p2) + $signed(sext_ln170_5_fu_936_p1));

assign add_ln700_19_fu_1607_p2 = ($signed(sext_ln170_8_fu_1017_p1) + $signed(sext_ln170_10_fu_1071_p1));

assign add_ln700_1_fu_1463_p2 = ($signed(sext_ln700_1_fu_1459_p1) + $signed(res_V_fu_776_p3));

assign add_ln700_20_fu_1617_p2 = ($signed(sext_ln170_9_fu_1044_p1) + $signed(sext_ln700_fu_1449_p1));

assign add_ln700_21_fu_1627_p2 = ($signed(sext_ln700_12_fu_1623_p1) + $signed(sext_ln700_11_fu_1613_p1));

assign add_ln700_22_fu_1633_p2 = ($signed(add_ln700_21_fu_1627_p2) + $signed(sext_ln700_10_fu_1603_p1));

assign add_ln700_23_fu_1643_p2 = ($signed(sext_ln700_13_fu_1639_p1) + $signed(sext_ln700_9_fu_1587_p1));

assign add_ln700_24_fu_1653_p2 = ($signed(sext_ln700_14_fu_1649_p1) + $signed(add_ln700_11_fu_1543_p2));

assign add_ln700_25_fu_2007_p2 = (zext_ln186_3_fu_1756_p1 + zext_ln186_5_fu_1775_p1);

assign add_ln700_26_fu_2013_p2 = (add_ln700_25_fu_2007_p2 + zext_ln186_1_fu_1737_p1);

assign add_ln700_27_fu_2023_p2 = (zext_ln186_7_fu_1794_p1 + zext_ln186_9_fu_1813_p1);

assign add_ln700_28_fu_2033_p2 = (zext_ln186_11_fu_1832_p1 + zext_ln186_13_fu_1851_p1);

assign add_ln700_29_fu_2043_p2 = (zext_ln700_3_fu_2039_p1 + zext_ln700_2_fu_2029_p1);

assign add_ln700_2_fu_1469_p2 = ($signed(sext_ln170_20_fu_1341_p1) + $signed(sext_ln170_17_fu_1260_p1));

assign add_ln700_30_fu_2049_p2 = (add_ln700_29_fu_2043_p2 + zext_ln700_1_fu_2019_p1);

assign add_ln700_31_fu_2059_p2 = (zext_ln186_15_fu_1870_p1 + zext_ln186_17_fu_1889_p1);

assign add_ln700_32_fu_2069_p2 = (zext_ln186_19_fu_1908_p1 + zext_ln186_21_fu_1927_p1);

assign add_ln700_33_fu_2079_p2 = (zext_ln700_6_fu_2075_p1 + zext_ln700_5_fu_2065_p1);

assign add_ln700_34_fu_2089_p2 = (zext_ln186_23_fu_1946_p1 + zext_ln186_25_fu_1965_p1);

assign add_ln700_35_fu_2099_p2 = (zext_ln186_27_fu_1984_p1 + zext_ln700_fu_2003_p1);

assign add_ln700_36_fu_2109_p2 = (zext_ln700_9_fu_2105_p1 + zext_ln700_8_fu_2095_p1);

assign add_ln700_37_fu_2119_p2 = (zext_ln700_10_fu_2115_p1 + zext_ln700_7_fu_2085_p1);

assign add_ln700_3_fu_1475_p2 = ($signed(add_ln700_2_fu_1469_p2) + $signed(sext_ln170_21_fu_1368_p1));

assign add_ln700_4_fu_1485_p2 = ($signed(sext_ln700_2_fu_1481_p1) + $signed(add_ln700_1_fu_1463_p2));

assign add_ln700_5_fu_1491_p2 = ($signed(sext_ln170_18_fu_1287_p1) + $signed(sext_ln170_11_fu_1098_p1));

assign add_ln700_6_fu_1497_p2 = ($signed(add_ln700_5_fu_1491_p2) + $signed(sext_ln170_19_fu_1314_p1));

assign add_ln700_7_fu_1507_p2 = ($signed(sext_ln170_13_fu_1152_p1) + $signed(sext_ln170_12_fu_1125_p1));

assign add_ln700_8_fu_1517_p2 = ($signed(sext_ln170_14_fu_1179_p1) + $signed(sext_ln170_16_fu_1233_p1));

assign add_ln700_9_fu_1527_p2 = ($signed(sext_ln700_5_fu_1523_p1) + $signed(sext_ln700_4_fu_1513_p1));

assign add_ln700_fu_1453_p2 = ($signed(sext_ln170_22_fu_1395_p1) + $signed(sext_ln170_23_fu_1422_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_487_p2 == 1'd0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_487_p2 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_487_p2 == 1'd0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_487_p2 == 1'd0)));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((out_V_V_TREADY == 1'b0) & (icmp_ln271_reg_2300 == 1'd1));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op26_read_state2 = ((icmp_ln252_fu_502_p2 == 1'd1) & (icmp_ln248_fu_487_p2 == 1'd0));
end

assign arg_V_read_assign_10_fu_1075_p4 = {{inElem_V_fu_248[47:44]}};

assign arg_V_read_assign_11_fu_1102_p4 = {{inElem_V_fu_248[51:48]}};

assign arg_V_read_assign_12_fu_1129_p4 = {{inElem_V_fu_248[55:52]}};

assign arg_V_read_assign_13_fu_1156_p4 = {{inElem_V_fu_248[59:56]}};

assign arg_V_read_assign_14_fu_1183_p4 = {{inElem_V_fu_248[63:60]}};

assign arg_V_read_assign_15_fu_1210_p4 = {{inElem_V_fu_248[67:64]}};

assign arg_V_read_assign_16_fu_1237_p4 = {{inElem_V_fu_248[71:68]}};

assign arg_V_read_assign_17_fu_1264_p4 = {{inElem_V_fu_248[75:72]}};

assign arg_V_read_assign_18_fu_1291_p4 = {{inElem_V_fu_248[79:76]}};

assign arg_V_read_assign_19_fu_1318_p4 = {{inElem_V_fu_248[83:80]}};

assign arg_V_read_assign_1_fu_805_p4 = {{inElem_V_fu_248[7:4]}};

assign arg_V_read_assign_20_fu_1345_p4 = {{inElem_V_fu_248[87:84]}};

assign arg_V_read_assign_21_fu_1372_p4 = {{inElem_V_fu_248[91:88]}};

assign arg_V_read_assign_22_fu_1399_p4 = {{inElem_V_fu_248[95:92]}};

assign arg_V_read_assign_23_fu_1426_p4 = {{inElem_V_fu_248[99:96]}};

assign arg_V_read_assign_2_fu_832_p4 = {{inElem_V_fu_248[11:8]}};

assign arg_V_read_assign_3_fu_859_p4 = {{inElem_V_fu_248[15:12]}};

assign arg_V_read_assign_4_fu_886_p4 = {{inElem_V_fu_248[19:16]}};

assign arg_V_read_assign_5_fu_913_p4 = {{inElem_V_fu_248[23:20]}};

assign arg_V_read_assign_6_fu_940_p4 = {{inElem_V_fu_248[27:24]}};

assign arg_V_read_assign_7_fu_967_p4 = {{inElem_V_fu_248[31:28]}};

assign arg_V_read_assign_8_fu_994_p4 = {{inElem_V_fu_248[35:32]}};

assign arg_V_read_assign_9_fu_1021_p4 = {{inElem_V_fu_248[39:36]}};

assign arg_V_read_assign_s_fu_1048_p4 = {{inElem_V_fu_248[43:40]}};

assign i_fu_493_p2 = (i_0_reg_466 + 13'd1);

assign icmp_ln248_fu_487_p2 = ((i_0_reg_466 == 13'd4704) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_502_p2 = ((ap_sig_allocacmp_nf_assign_load_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_770_p2 = ((sf_1_fu_240 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_1703_p2 = ((nf_fu_1697_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln899_10_fu_1916_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_20_fu_1912_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_11_fu_1935_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_22_fu_1931_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_12_fu_1954_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_24_fu_1950_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_13_fu_1973_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_26_fu_1969_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_14_fu_1992_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_28_fu_1988_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_1745_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_2_fu_1741_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_2_fu_1764_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_4_fu_1760_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_3_fu_1783_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_6_fu_1779_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_4_fu_1802_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_8_fu_1798_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_5_fu_1821_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_10_fu_1817_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_6_fu_1840_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_12_fu_1836_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_7_fu_1859_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_14_fu_1855_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_8_fu_1878_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_16_fu_1874_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_9_fu_1897_p2 = (($signed(add_ln700_24_reg_2304) < $signed(zext_ln186_18_fu_1893_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_1726_p2 = (($signed(add_ln700_24_reg_2304) < $signed(sext_ln186_fu_1722_p1)) ? 1'b1 : 1'b0);

assign nf_1_fu_1709_p3 = ((icmp_ln301_fu_1703_p2[0:0] === 1'b1) ? 32'd0 : nf_fu_1697_p2);

assign nf_fu_1697_p2 = (nf_assign_fu_244 + 32'd1);

assign out_V_V_TDATA = tmp_V_fu_2125_p2;

assign res_V_fu_776_p3 = ((icmp_ln271_fu_770_p2[0:0] === 1'b1) ? 11'd0 : accu_V_0_0_0_fu_236);

assign sext_ln170_10_fu_1071_p1 = mul_ln1352_10_fu_1065_p2;

assign sext_ln170_11_fu_1098_p1 = mul_ln1352_11_fu_1092_p2;

assign sext_ln170_12_fu_1125_p1 = mul_ln1352_12_fu_1119_p2;

assign sext_ln170_13_fu_1152_p1 = mul_ln1352_13_fu_1146_p2;

assign sext_ln170_14_fu_1179_p1 = mul_ln1352_14_fu_1173_p2;

assign sext_ln170_15_fu_1206_p1 = mul_ln1352_15_fu_1200_p2;

assign sext_ln170_16_fu_1233_p1 = mul_ln1352_16_fu_1227_p2;

assign sext_ln170_17_fu_1260_p1 = mul_ln1352_17_fu_1254_p2;

assign sext_ln170_18_fu_1287_p1 = mul_ln1352_18_fu_1281_p2;

assign sext_ln170_19_fu_1314_p1 = mul_ln1352_19_fu_1308_p2;

assign sext_ln170_1_fu_828_p1 = mul_ln1352_1_fu_822_p2;

assign sext_ln170_20_fu_1341_p1 = mul_ln1352_20_fu_1335_p2;

assign sext_ln170_21_fu_1368_p1 = mul_ln1352_21_fu_1362_p2;

assign sext_ln170_22_fu_1395_p1 = mul_ln1352_22_fu_1389_p2;

assign sext_ln170_23_fu_1422_p1 = mul_ln1352_23_fu_1416_p2;

assign sext_ln170_2_fu_855_p1 = mul_ln1352_2_fu_849_p2;

assign sext_ln170_3_fu_882_p1 = mul_ln1352_3_fu_876_p2;

assign sext_ln170_4_fu_909_p1 = mul_ln1352_4_fu_903_p2;

assign sext_ln170_5_fu_936_p1 = mul_ln1352_5_fu_930_p2;

assign sext_ln170_6_fu_963_p1 = mul_ln1352_6_fu_957_p2;

assign sext_ln170_7_fu_990_p1 = mul_ln1352_7_fu_984_p2;

assign sext_ln170_8_fu_1017_p1 = mul_ln1352_8_fu_1011_p2;

assign sext_ln170_9_fu_1044_p1 = mul_ln1352_9_fu_1038_p2;

assign sext_ln170_fu_801_p1 = mul_ln1352_fu_795_p2;

assign sext_ln186_fu_1722_p1 = $signed(threshs_m_thresholds_14_q0);

assign sext_ln700_10_fu_1603_p1 = $signed(add_ln700_18_fu_1597_p2);

assign sext_ln700_11_fu_1613_p1 = $signed(add_ln700_19_fu_1607_p2);

assign sext_ln700_12_fu_1623_p1 = $signed(add_ln700_20_fu_1617_p2);

assign sext_ln700_13_fu_1639_p1 = $signed(add_ln700_22_fu_1633_p2);

assign sext_ln700_14_fu_1649_p1 = $signed(add_ln700_23_fu_1643_p2);

assign sext_ln700_1_fu_1459_p1 = $signed(add_ln700_fu_1453_p2);

assign sext_ln700_2_fu_1481_p1 = $signed(add_ln700_3_fu_1475_p2);

assign sext_ln700_3_fu_1503_p1 = $signed(add_ln700_6_fu_1497_p2);

assign sext_ln700_4_fu_1513_p1 = $signed(add_ln700_7_fu_1507_p2);

assign sext_ln700_5_fu_1523_p1 = $signed(add_ln700_8_fu_1517_p2);

assign sext_ln700_6_fu_1539_p1 = $signed(add_ln700_10_fu_1533_p2);

assign sext_ln700_7_fu_1561_p1 = $signed(add_ln700_13_fu_1555_p2);

assign sext_ln700_8_fu_1577_p1 = $signed(add_ln700_15_fu_1571_p2);

assign sext_ln700_9_fu_1587_p1 = $signed(add_ln700_16_fu_1581_p2);

assign sext_ln700_fu_1449_p1 = mul_ln1352_24_fu_1443_p2;

assign sf_fu_1659_p2 = (32'd1 + sf_1_fu_240);

assign threshs_m_thresholds_10_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_11_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_12_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_13_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_14_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_1_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_2_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_3_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_4_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_5_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_6_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_7_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_8_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_9_address0 = zext_ln186_fu_1678_p1;

assign threshs_m_thresholds_address0 = zext_ln186_fu_1678_p1;

assign tmp_V_2_fu_508_p1 = in_V_V_TDATA[99:0];

assign tmp_V_fu_2125_p2 = (add_ln700_37_fu_2119_p2 + zext_ln700_4_fu_2055_p1);

assign trunc_ln647_fu_784_p1 = inElem_V_fu_248[3:0];

assign wgt_M_instance_0_V_fu_517_p1 = weight_V_V_TDATA[2:0];

assign xor_ln899_10_fu_1921_p2 = (icmp_ln899_10_fu_1916_p2 ^ 1'd1);

assign xor_ln899_11_fu_1940_p2 = (icmp_ln899_11_fu_1935_p2 ^ 1'd1);

assign xor_ln899_12_fu_1959_p2 = (icmp_ln899_12_fu_1954_p2 ^ 1'd1);

assign xor_ln899_13_fu_1978_p2 = (icmp_ln899_13_fu_1973_p2 ^ 1'd1);

assign xor_ln899_14_fu_1997_p2 = (icmp_ln899_14_fu_1992_p2 ^ 1'd1);

assign xor_ln899_1_fu_1750_p2 = (icmp_ln899_1_fu_1745_p2 ^ 1'd1);

assign xor_ln899_2_fu_1769_p2 = (icmp_ln899_2_fu_1764_p2 ^ 1'd1);

assign xor_ln899_3_fu_1788_p2 = (icmp_ln899_3_fu_1783_p2 ^ 1'd1);

assign xor_ln899_4_fu_1807_p2 = (icmp_ln899_4_fu_1802_p2 ^ 1'd1);

assign xor_ln899_5_fu_1826_p2 = (icmp_ln899_5_fu_1821_p2 ^ 1'd1);

assign xor_ln899_6_fu_1845_p2 = (icmp_ln899_6_fu_1840_p2 ^ 1'd1);

assign xor_ln899_7_fu_1864_p2 = (icmp_ln899_7_fu_1859_p2 ^ 1'd1);

assign xor_ln899_8_fu_1883_p2 = (icmp_ln899_8_fu_1878_p2 ^ 1'd1);

assign xor_ln899_9_fu_1902_p2 = (icmp_ln899_9_fu_1897_p2 ^ 1'd1);

assign xor_ln899_fu_1731_p2 = (icmp_ln899_fu_1726_p2 ^ 1'd1);

assign zext_ln186_10_fu_1817_p1 = threshs_m_thresholds_4_q0;

assign zext_ln186_11_fu_1832_p1 = xor_ln899_5_fu_1826_p2;

assign zext_ln186_12_fu_1836_p1 = threshs_m_thresholds_3_q0;

assign zext_ln186_13_fu_1851_p1 = xor_ln899_6_fu_1845_p2;

assign zext_ln186_14_fu_1855_p1 = threshs_m_thresholds_2_q0;

assign zext_ln186_15_fu_1870_p1 = xor_ln899_7_fu_1864_p2;

assign zext_ln186_16_fu_1874_p1 = threshs_m_thresholds_1_q0;

assign zext_ln186_17_fu_1889_p1 = xor_ln899_8_fu_1883_p2;

assign zext_ln186_18_fu_1893_p1 = threshs_m_thresholds_q0;

assign zext_ln186_19_fu_1908_p1 = xor_ln899_9_fu_1902_p2;

assign zext_ln186_1_fu_1737_p1 = xor_ln899_fu_1731_p2;

assign zext_ln186_20_fu_1912_p1 = threshs_m_thresholds_12_q0;

assign zext_ln186_21_fu_1927_p1 = xor_ln899_10_fu_1921_p2;

assign zext_ln186_22_fu_1931_p1 = threshs_m_thresholds_11_q0;

assign zext_ln186_23_fu_1946_p1 = xor_ln899_11_fu_1940_p2;

assign zext_ln186_24_fu_1950_p1 = threshs_m_thresholds_10_q0;

assign zext_ln186_25_fu_1965_p1 = xor_ln899_12_fu_1959_p2;

assign zext_ln186_26_fu_1969_p1 = threshs_m_thresholds_9_q0;

assign zext_ln186_27_fu_1984_p1 = xor_ln899_13_fu_1978_p2;

assign zext_ln186_28_fu_1988_p1 = threshs_m_thresholds_8_q0;

assign zext_ln186_2_fu_1741_p1 = threshs_m_thresholds_13_q0;

assign zext_ln186_3_fu_1756_p1 = xor_ln899_1_fu_1750_p2;

assign zext_ln186_4_fu_1760_p1 = threshs_m_thresholds_7_q0;

assign zext_ln186_5_fu_1775_p1 = xor_ln899_2_fu_1769_p2;

assign zext_ln186_6_fu_1779_p1 = threshs_m_thresholds_6_q0;

assign zext_ln186_7_fu_1794_p1 = xor_ln899_3_fu_1788_p2;

assign zext_ln186_8_fu_1798_p1 = threshs_m_thresholds_5_q0;

assign zext_ln186_9_fu_1813_p1 = xor_ln899_4_fu_1807_p2;

assign zext_ln186_fu_1678_p1 = nf_assign_fu_244;

assign zext_ln700_10_fu_2115_p1 = add_ln700_36_fu_2109_p2;

assign zext_ln700_1_fu_2019_p1 = add_ln700_26_fu_2013_p2;

assign zext_ln700_2_fu_2029_p1 = add_ln700_27_fu_2023_p2;

assign zext_ln700_3_fu_2039_p1 = add_ln700_28_fu_2033_p2;

assign zext_ln700_4_fu_2055_p1 = add_ln700_30_fu_2049_p2;

assign zext_ln700_5_fu_2065_p1 = add_ln700_31_fu_2059_p2;

assign zext_ln700_6_fu_2075_p1 = add_ln700_32_fu_2069_p2;

assign zext_ln700_7_fu_2085_p1 = add_ln700_33_fu_2079_p2;

assign zext_ln700_8_fu_2095_p1 = add_ln700_34_fu_2089_p2;

assign zext_ln700_9_fu_2105_p1 = add_ln700_35_fu_2099_p2;

assign zext_ln700_fu_2003_p1 = xor_ln899_14_fu_1997_p2;

endmodule //StreamingFCLayer_Batch_0_Matrix_Vector_Activa
