// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGenerator_1_ConvolutionInputGene_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln197_fu_438_p2;
wire   [0:0] icmp_ln199_fu_460_p2;
wire   [0:0] and_ln245_fu_700_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln199_reg_1019;
reg   [0:0] icmp_ln215_reg_1023;
reg   [13:0] i_0_0_reg_341;
reg    ap_predicate_op129_read_state2;
reg    ap_predicate_op179_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_predicate_op232_write_state3;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [13:0] add_ln197_fu_444_p2;
wire   [0:0] icmp_ln215_fu_469_p2;
wire   [2:0] select_ln217_fu_531_p3;
reg   [2:0] select_ln217_reg_1027;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [6:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [3:0] inputBuf_0_V_q0;
reg   [6:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
reg   [3:0] inputBuf_0_V_d1;
wire   [6:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [3:0] inputBuf_1_V_q0;
reg   [6:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
reg   [3:0] inputBuf_1_V_d1;
wire   [6:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [3:0] inputBuf_2_V_q0;
reg   [6:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
reg   [3:0] inputBuf_2_V_d1;
wire   [6:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [3:0] inputBuf_3_V_q0;
reg   [6:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
reg   [3:0] inputBuf_3_V_d1;
wire   [6:0] inputBuf_4_V_address0;
reg    inputBuf_4_V_ce0;
wire   [3:0] inputBuf_4_V_q0;
reg   [6:0] inputBuf_4_V_address1;
reg    inputBuf_4_V_ce1;
reg    inputBuf_4_V_we1;
reg   [3:0] inputBuf_4_V_d1;
wire   [6:0] inputBuf_5_V_address0;
reg    inputBuf_5_V_ce0;
wire   [3:0] inputBuf_5_V_q0;
reg   [6:0] inputBuf_5_V_address1;
reg    inputBuf_5_V_ce1;
reg    inputBuf_5_V_we1;
reg   [3:0] inputBuf_5_V_d1;
wire   [63:0] zext_ln221_fu_569_p1;
wire   [63:0] zext_ln248_fu_716_p1;
wire   [63:0] zext_ln202_fu_840_p1;
reg   [31:0] ofm_y_1_0_fu_84;
wire   [31:0] select_ln236_1_fu_667_p3;
wire   [0:0] icmp_ln224_fu_585_p2;
wire   [0:0] icmp_ln227_fu_602_p2;
wire   [0:0] icmp_ln230_fu_613_p2;
wire   [0:0] icmp_ln233_fu_633_p2;
reg   [31:0] ofm_x_1_0_fu_88;
wire   [31:0] add_ln232_fu_627_p2;
reg   [31:0] k_y_1_0_fu_92;
wire   [31:0] add_ln216_fu_491_p2;
reg   [31:0] inp_15_0_fu_96;
wire   [31:0] select_ln236_fu_659_p3;
wire   [31:0] add_ln204_fu_854_p2;
reg   [31:0] k_x_1_0_fu_100;
wire   [31:0] add_ln226_fu_596_p2;
reg   [31:0] count_simd_1_0_fu_104;
wire   [31:0] add_ln223_fu_579_p2;
reg   [31:0] read_block_1_0_fu_108;
wire   [31:0] zext_ln252_fu_783_p1;
wire   [31:0] add_ln211_fu_890_p2;
wire   [0:0] icmp_ln205_fu_412_p2;
reg   [31:0] current_block_write_s_fu_112;
wire   [31:0] select_ln252_fu_759_p3;
wire   [31:0] select_ln208_fu_882_p3;
reg   [31:0] current_line_1_0_fu_116;
wire   [31:0] select_ln252_1_fu_767_p3;
wire   [31:0] grp_fu_400_p2;
reg   [31:0] counter_internal_blo_fu_120;
wire   [31:0] select_ln264_fu_817_p3;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] trunc_ln321_1_fu_726_p1;
wire   [3:0] tmp_V_2_fu_706_p1;
wire   [2:0] trunc_ln321_fu_850_p1;
wire   [3:0] tmp_V_fu_830_p1;
wire   [31:0] add_ln216_1_fu_501_p2;
wire   [2:0] trunc_ln216_1_fu_497_p1;
wire   [2:0] add_ln218_1_fu_513_p2;
wire   [2:0] trunc_ln216_fu_487_p1;
wire   [2:0] add_ln218_fu_519_p2;
wire   [0:0] icmp_ln217_fu_507_p2;
wire   [2:0] add_ln217_fu_525_p2;
wire   [31:0] add_ln220_fu_539_p2;
wire   [31:0] shl_ln220_fu_545_p2;
wire   [31:0] shl_ln220_1_fu_551_p2;
wire   [31:0] sub_ln220_fu_557_p2;
wire   [31:0] add_ln220_1_fu_563_p2;
wire   [31:0] add_ln235_fu_647_p2;
wire   [0:0] icmp_ln236_fu_653_p2;
wire   [0:0] icmp_ln245_fu_688_p2;
wire   [0:0] icmp_ln245_1_fu_694_p2;
wire   [3:0] trunc_ln197_fu_456_p1;
wire   [31:0] add_ln256_fu_739_p2;
wire   [0:0] icmp_ln257_fu_745_p2;
wire   [0:0] icmp_ln252_fu_406_p2;
wire   [31:0] select_ln257_fu_751_p3;
wire   [3:0] add_ln256_1_fu_733_p2;
wire   [3:0] select_ln252_2_fu_775_p3;
wire   [31:0] add_ln263_fu_805_p2;
wire   [0:0] icmp_ln264_fu_811_p2;
wire   [31:0] add_ln207_fu_870_p2;
wire   [0:0] icmp_ln208_fu_876_p2;
wire   [3:0] tmp_V_1_fu_906_p8;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op140_store_state2;
reg    ap_enable_operation_140;
reg    ap_enable_state2_pp0_iter0_stage0;
reg    ap_predicate_op79_load_state2;
reg    ap_enable_operation_79;
reg    ap_predicate_op228_load_state3;
reg    ap_enable_operation_228;
reg    ap_enable_state3_pp0_iter1_stage0;
reg    ap_predicate_op190_store_state2;
reg    ap_enable_operation_190;
reg    ap_predicate_op142_store_state2;
reg    ap_enable_operation_142;
reg    ap_predicate_op77_load_state2;
reg    ap_enable_operation_77;
reg    ap_predicate_op227_load_state3;
reg    ap_enable_operation_227;
reg    ap_predicate_op192_store_state2;
reg    ap_enable_operation_192;
reg    ap_predicate_op144_store_state2;
reg    ap_enable_operation_144;
reg    ap_predicate_op75_load_state2;
reg    ap_enable_operation_75;
reg    ap_predicate_op226_load_state3;
reg    ap_enable_operation_226;
reg    ap_predicate_op194_store_state2;
reg    ap_enable_operation_194;
reg    ap_predicate_op146_store_state2;
reg    ap_enable_operation_146;
reg    ap_predicate_op73_load_state2;
reg    ap_enable_operation_73;
reg    ap_predicate_op225_load_state3;
reg    ap_enable_operation_225;
reg    ap_predicate_op196_store_state2;
reg    ap_enable_operation_196;
reg    ap_predicate_op148_store_state2;
reg    ap_enable_operation_148;
reg    ap_predicate_op71_load_state2;
reg    ap_enable_operation_71;
reg    ap_predicate_op224_load_state3;
reg    ap_enable_operation_224;
reg    ap_predicate_op198_store_state2;
reg    ap_enable_operation_198;
reg    ap_predicate_op150_store_state2;
reg    ap_enable_operation_150;
reg    ap_predicate_op81_load_state2;
reg    ap_enable_operation_81;
reg    ap_predicate_op229_load_state3;
reg    ap_enable_operation_229;
reg    ap_predicate_op200_store_state2;
reg    ap_enable_operation_200;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_774;
reg    ap_condition_260;
reg    ap_condition_780;
reg    ap_condition_784;
reg    ap_condition_788;
reg    ap_condition_792;
reg    ap_condition_800;
reg    ap_condition_807;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(inputBuf_0_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(inputBuf_1_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(inputBuf_2_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(inputBuf_3_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_4_V_address0),
    .ce0(inputBuf_4_V_ce0),
    .q0(inputBuf_4_V_q0),
    .address1(inputBuf_4_V_address1),
    .ce1(inputBuf_4_V_ce1),
    .we1(inputBuf_4_V_we1),
    .d1(inputBuf_4_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGbkb #(
    .DataWidth( 4 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_5_V_address0),
    .ce0(inputBuf_5_V_ce0),
    .q0(inputBuf_5_V_q0),
    .address1(inputBuf_5_V_address1),
    .ce1(inputBuf_5_V_ce1),
    .we1(inputBuf_5_V_we1),
    .d1(inputBuf_5_V_d1)
);

ConvolutionInputGenerator_1_ConvolutionInputGhbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 4 ),
    .din5_WIDTH( 4 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
ConvolutionInputGhbi_U1(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(inputBuf_4_V_q0),
    .din5(inputBuf_5_V_q0),
    .din6(select_ln217_reg_1027),
    .dout(tmp_V_1_fu_906_p8)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln224_fu_585_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_simd_1_0_fu_104 <= add_ln223_fu_579_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln227_fu_602_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln230_fu_613_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln233_fu_633_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln233_fu_633_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_1_0_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_internal_blo_fu_120 <= select_ln264_fu_817_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_412_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_120 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_412_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_112 <= select_ln208_fu_882_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_112 <= select_ln252_fu_759_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_s_fu_112 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln205_fu_412_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_1_0_fu_116 <= grp_fu_400_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_1_0_fu_116 <= select_ln252_1_fu_767_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_412_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_1_0_fu_116 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_0_reg_341 <= 14'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_0_reg_341 <= add_ln197_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_15_0_fu_96 <= add_ln204_fu_854_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln233_fu_633_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_15_0_fu_96 <= select_ln236_fu_659_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_15_0_fu_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln227_fu_602_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_x_1_0_fu_100 <= add_ln226_fu_596_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln230_fu_613_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln233_fu_633_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln233_fu_633_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_1_0_fu_100 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln230_fu_613_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_y_1_0_fu_92 <= add_ln216_fu_491_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_1_0_fu_92 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln233_fu_633_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_x_1_0_fu_88 <= add_ln232_fu_627_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln233_fu_633_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_1_0_fu_88 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln233_fu_633_p2 == 1'd1) & (icmp_ln230_fu_613_p2 == 1'd1) & (icmp_ln227_fu_602_p2 == 1'd1) & (icmp_ln224_fu_585_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_y_1_0_fu_84 <= select_ln236_1_fu_667_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_0_fu_84 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln205_fu_412_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_108 <= add_ln211_fu_890_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_108 <= zext_ln252_fu_783_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_1_0_fu_108 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln197_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln199_reg_1019 <= icmp_ln199_fu_460_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln215_reg_1023 <= icmp_ln215_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln217_reg_1027 <= select_ln217_fu_531_p3;
    end
end

always @ (*) begin
    if ((icmp_ln197_fu_438_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op179_read_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op129_read_state2 == 1'b1)))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd0))) begin
            inputBuf_0_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_774)) begin
            inputBuf_0_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd0))) begin
            inputBuf_0_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_774)) begin
            inputBuf_0_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_0_V_d1 = 'bx;
        end
    end else begin
        inputBuf_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd1))) begin
            inputBuf_1_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_780)) begin
            inputBuf_1_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd1))) begin
            inputBuf_1_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_780)) begin
            inputBuf_1_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_1_V_d1 = 'bx;
        end
    end else begin
        inputBuf_1_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd2))) begin
            inputBuf_2_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_784)) begin
            inputBuf_2_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd2))) begin
            inputBuf_2_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_784)) begin
            inputBuf_2_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_2_V_d1 = 'bx;
        end
    end else begin
        inputBuf_2_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd3))) begin
            inputBuf_3_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_788)) begin
            inputBuf_3_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd3))) begin
            inputBuf_3_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_788)) begin
            inputBuf_3_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_3_V_d1 = 'bx;
        end
    end else begin
        inputBuf_3_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd4))) begin
            inputBuf_4_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_792)) begin
            inputBuf_4_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_4_V_address1 = 'bx;
        end
    end else begin
        inputBuf_4_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_4_V_ce0 = 1'b1;
    end else begin
        inputBuf_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_4_V_ce1 = 1'b1;
    end else begin
        inputBuf_4_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if (((icmp_ln199_fu_460_p2 == 1'd1) & (trunc_ln321_fu_850_p1 == 3'd4))) begin
            inputBuf_4_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_792)) begin
            inputBuf_4_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_4_V_d1 = 'bx;
        end
    end else begin
        inputBuf_4_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_4_V_we1 = 1'b1;
    end else begin
        inputBuf_4_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if ((1'b1 == ap_condition_807)) begin
            inputBuf_5_V_address1 = zext_ln202_fu_840_p1;
        end else if ((1'b1 == ap_condition_800)) begin
            inputBuf_5_V_address1 = zext_ln248_fu_716_p1;
        end else begin
            inputBuf_5_V_address1 = 'bx;
        end
    end else begin
        inputBuf_5_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_5_V_ce0 = 1'b1;
    end else begin
        inputBuf_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln321_1_fu_726_p1 == 3'd4) & ~(trunc_ln321_1_fu_726_p1 == 3'd3) & ~(trunc_ln321_1_fu_726_p1 == 3'd2) & ~(trunc_ln321_1_fu_726_p1 == 3'd1) & ~(trunc_ln321_1_fu_726_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln321_fu_850_p1 == 3'd4) & ~(trunc_ln321_fu_850_p1 == 3'd3) & ~(trunc_ln321_fu_850_p1 == 3'd2) & ~(trunc_ln321_fu_850_p1 == 3'd1) & ~(trunc_ln321_fu_850_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_5_V_ce1 = 1'b1;
    end else begin
        inputBuf_5_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_260)) begin
        if ((1'b1 == ap_condition_807)) begin
            inputBuf_5_V_d1 = tmp_V_fu_830_p1;
        end else if ((1'b1 == ap_condition_800)) begin
            inputBuf_5_V_d1 = tmp_V_2_fu_706_p1;
        end else begin
            inputBuf_5_V_d1 = 'bx;
        end
    end else begin
        inputBuf_5_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln321_1_fu_726_p1 == 3'd4) & ~(trunc_ln321_1_fu_726_p1 == 3'd3) & ~(trunc_ln321_1_fu_726_p1 == 3'd2) & ~(trunc_ln321_1_fu_726_p1 == 3'd1) & ~(trunc_ln321_1_fu_726_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln321_fu_850_p1 == 3'd4) & ~(trunc_ln321_fu_850_p1 == 3'd3) & ~(trunc_ln321_fu_850_p1 == 3'd2) & ~(trunc_ln321_fu_850_p1 == 3'd1) & ~(trunc_ln321_fu_850_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_5_V_we1 = 1'b1;
    end else begin
        inputBuf_5_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op232_write_state3 == 1'b1))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln197_fu_438_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln197_fu_438_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln197_fu_444_p2 = (i_0_0_reg_341 + 14'd1);

assign add_ln204_fu_854_p2 = (inp_15_0_fu_96 + 32'd1);

assign add_ln207_fu_870_p2 = (current_block_write_s_fu_112 + 32'd1);

assign add_ln211_fu_890_p2 = (read_block_1_0_fu_108 + 32'd1);

assign add_ln216_1_fu_501_p2 = (current_block_write_s_fu_112 + add_ln216_fu_491_p2);

assign add_ln216_fu_491_p2 = (32'd1 + k_y_1_0_fu_92);

assign add_ln217_fu_525_p2 = (3'd2 + add_ln218_fu_519_p2);

assign add_ln218_1_fu_513_p2 = (3'd1 + trunc_ln216_1_fu_497_p1);

assign add_ln218_fu_519_p2 = (add_ln218_1_fu_513_p2 + trunc_ln216_fu_487_p1);

assign add_ln220_1_fu_563_p2 = (sub_ln220_fu_557_p2 + count_simd_1_0_fu_104);

assign add_ln220_fu_539_p2 = (k_x_1_0_fu_100 + ofm_x_1_0_fu_88);

assign add_ln223_fu_579_p2 = (32'd1 + count_simd_1_0_fu_104);

assign add_ln226_fu_596_p2 = (k_x_1_0_fu_100 + 32'd1);

assign add_ln232_fu_627_p2 = (ofm_x_1_0_fu_88 + 32'd1);

assign add_ln235_fu_647_p2 = (ofm_y_1_0_fu_84 + 32'd1);

assign add_ln256_1_fu_733_p2 = (trunc_ln197_fu_456_p1 + 4'd1);

assign add_ln256_fu_739_p2 = (current_block_write_s_fu_112 + 32'd1);

assign add_ln263_fu_805_p2 = (counter_internal_blo_fu_120 + 32'd1);

assign and_ln245_fu_700_p2 = (icmp_ln245_fu_688_p2 & icmp_ln245_1_fu_694_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op179_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op129_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op179_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op129_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op179_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op129_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op179_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op129_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = ((out_V_V_TREADY == 1'b0) & (ap_predicate_op232_write_state3 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_260 = ((icmp_ln197_fu_438_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_774 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd0));
end

always @ (*) begin
    ap_condition_780 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd1));
end

always @ (*) begin
    ap_condition_784 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd2));
end

always @ (*) begin
    ap_condition_788 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd3));
end

always @ (*) begin
    ap_condition_792 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd4));
end

always @ (*) begin
    ap_condition_800 = (~(trunc_ln321_1_fu_726_p1 == 3'd4) & ~(trunc_ln321_1_fu_726_p1 == 3'd3) & ~(trunc_ln321_1_fu_726_p1 == 3'd2) & ~(trunc_ln321_1_fu_726_p1 == 3'd1) & ~(trunc_ln321_1_fu_726_p1 == 3'd0) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_807 = (~(trunc_ln321_fu_850_p1 == 3'd4) & ~(trunc_ln321_fu_850_p1 == 3'd3) & ~(trunc_ln321_fu_850_p1 == 3'd2) & ~(trunc_ln321_fu_850_p1 == 3'd1) & ~(trunc_ln321_fu_850_p1 == 3'd0) & (icmp_ln199_fu_460_p2 == 1'd1));
end

always @ (*) begin
    ap_enable_operation_140 = (ap_predicate_op140_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_142 = (ap_predicate_op142_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_144 = (ap_predicate_op144_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_146 = (ap_predicate_op146_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_148 = (ap_predicate_op148_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_150 = (ap_predicate_op150_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_190 = (ap_predicate_op190_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_192 = (ap_predicate_op192_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_194 = (ap_predicate_op194_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_196 = (ap_predicate_op196_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_198 = (ap_predicate_op198_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_200 = (ap_predicate_op200_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_224 = (ap_predicate_op224_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_225 = (ap_predicate_op225_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_226 = (ap_predicate_op226_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_227 = (ap_predicate_op227_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_228 = (ap_predicate_op228_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_229 = (ap_predicate_op229_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_71 = (ap_predicate_op71_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_73 = (ap_predicate_op73_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_75 = (ap_predicate_op75_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_77 = (ap_predicate_op77_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_79 = (ap_predicate_op79_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_81 = (ap_predicate_op81_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state2_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op129_read_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op140_store_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd4));
end

always @ (*) begin
    ap_predicate_op142_store_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd3));
end

always @ (*) begin
    ap_predicate_op144_store_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd2));
end

always @ (*) begin
    ap_predicate_op146_store_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd1));
end

always @ (*) begin
    ap_predicate_op148_store_state2 = ((1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_1_fu_726_p1 == 3'd0));
end

always @ (*) begin
    ap_predicate_op150_store_state2 = (~(trunc_ln321_1_fu_726_p1 == 3'd4) & ~(trunc_ln321_1_fu_726_p1 == 3'd3) & ~(trunc_ln321_1_fu_726_p1 == 3'd2) & ~(trunc_ln321_1_fu_726_p1 == 3'd1) & ~(trunc_ln321_1_fu_726_p1 == 3'd0) & (1'd1 == and_ln245_fu_700_p2) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op179_read_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_store_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd4));
end

always @ (*) begin
    ap_predicate_op192_store_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd3));
end

always @ (*) begin
    ap_predicate_op194_store_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd2));
end

always @ (*) begin
    ap_predicate_op196_store_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd1));
end

always @ (*) begin
    ap_predicate_op198_store_state2 = ((icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0) & (trunc_ln321_fu_850_p1 == 3'd0));
end

always @ (*) begin
    ap_predicate_op200_store_state2 = (~(trunc_ln321_fu_850_p1 == 3'd4) & ~(trunc_ln321_fu_850_p1 == 3'd3) & ~(trunc_ln321_fu_850_p1 == 3'd2) & ~(trunc_ln321_fu_850_p1 == 3'd1) & ~(trunc_ln321_fu_850_p1 == 3'd0) & (icmp_ln199_fu_460_p2 == 1'd1) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op224_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op225_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op226_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op227_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_load_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op232_write_state3 = ((icmp_ln215_reg_1023 == 1'd1) & (icmp_ln199_reg_1019 == 1'd0));
end

always @ (*) begin
    ap_predicate_op71_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op73_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op75_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op77_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op79_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op81_load_state2 = ((icmp_ln215_fu_469_p2 == 1'd1) & (icmp_ln199_fu_460_p2 == 1'd0) & (icmp_ln197_fu_438_p2 == 1'd0));
end

assign grp_fu_400_p2 = (current_line_1_0_fu_116 + 32'd1);

assign icmp_ln197_fu_438_p2 = ((i_0_0_reg_341 == 14'd15420) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_460_p2 = ((inp_15_0_fu_96 < 32'd420) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_412_p2 = ((grp_fu_400_p2 == 32'd84) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_876_p2 = ((add_ln207_fu_870_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_469_p2 = ((counter_internal_blo_fu_120 < 32'd1499) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_507_p2 = ((add_ln216_1_fu_501_p2 > 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_585_p2 = ((add_ln223_fu_579_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_602_p2 = ((add_ln226_fu_596_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_613_p2 = ((add_ln216_fu_491_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_633_p2 = ((add_ln232_fu_627_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_653_p2 = ((add_ln235_fu_647_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln245_1_fu_694_p2 = ((read_block_1_0_fu_108 < 32'd14) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_688_p2 = ((counter_internal_blo_fu_120 < 32'd83) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_406_p2 = ((grp_fu_400_p2 == 32'd84) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_745_p2 = ((add_ln256_fu_739_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln264_fu_811_p2 = ((add_ln263_fu_805_p2 == 32'd1499) ? 1'b1 : 1'b0);

assign inputBuf_0_V_address0 = zext_ln221_fu_569_p1;

assign inputBuf_1_V_address0 = zext_ln221_fu_569_p1;

assign inputBuf_2_V_address0 = zext_ln221_fu_569_p1;

assign inputBuf_3_V_address0 = zext_ln221_fu_569_p1;

assign inputBuf_4_V_address0 = zext_ln221_fu_569_p1;

assign inputBuf_5_V_address0 = zext_ln221_fu_569_p1;

assign out_V_V_TDATA = tmp_V_1_fu_906_p8;

assign select_ln208_fu_882_p3 = ((icmp_ln208_fu_876_p2[0:0] === 1'b1) ? 32'd0 : add_ln207_fu_870_p2);

assign select_ln217_fu_531_p3 = ((icmp_ln217_fu_507_p2[0:0] === 1'b1) ? add_ln217_fu_525_p2 : add_ln218_fu_519_p2);

assign select_ln236_1_fu_667_p3 = ((icmp_ln236_fu_653_p2[0:0] === 1'b1) ? 32'd0 : add_ln235_fu_647_p2);

assign select_ln236_fu_659_p3 = ((icmp_ln236_fu_653_p2[0:0] === 1'b1) ? 32'd0 : inp_15_0_fu_96);

assign select_ln252_1_fu_767_p3 = ((icmp_ln252_fu_406_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_400_p2);

assign select_ln252_2_fu_775_p3 = ((icmp_ln252_fu_406_p2[0:0] === 1'b1) ? add_ln256_1_fu_733_p2 : trunc_ln197_fu_456_p1);

assign select_ln252_fu_759_p3 = ((icmp_ln252_fu_406_p2[0:0] === 1'b1) ? select_ln257_fu_751_p3 : current_block_write_s_fu_112);

assign select_ln257_fu_751_p3 = ((icmp_ln257_fu_745_p2[0:0] === 1'b1) ? 32'd0 : add_ln256_fu_739_p2);

assign select_ln264_fu_817_p3 = ((icmp_ln264_fu_811_p2[0:0] === 1'b1) ? 32'd0 : add_ln263_fu_805_p2);

assign shl_ln220_1_fu_551_p2 = add_ln220_fu_539_p2 << 32'd1;

assign shl_ln220_fu_545_p2 = add_ln220_fu_539_p2 << 32'd3;

assign sub_ln220_fu_557_p2 = (shl_ln220_fu_545_p2 - shl_ln220_1_fu_551_p2);

assign tmp_V_2_fu_706_p1 = in_V_V_TDATA[3:0];

assign tmp_V_fu_830_p1 = in_V_V_TDATA[3:0];

assign trunc_ln197_fu_456_p1 = read_block_1_0_fu_108[3:0];

assign trunc_ln216_1_fu_497_p1 = current_block_write_s_fu_112[2:0];

assign trunc_ln216_fu_487_p1 = k_y_1_0_fu_92[2:0];

assign trunc_ln321_1_fu_726_p1 = current_block_write_s_fu_112[2:0];

assign trunc_ln321_fu_850_p1 = current_block_write_s_fu_112[2:0];

assign zext_ln202_fu_840_p1 = current_line_1_0_fu_116;

assign zext_ln221_fu_569_p1 = add_ln220_1_fu_563_p2;

assign zext_ln248_fu_716_p1 = current_line_1_0_fu_116;

assign zext_ln252_fu_783_p1 = select_ln252_2_fu_775_p3;

endmodule //ConvolutionInputGenerator_1_ConvolutionInputGene_1
